### ISSUE TITLE
[AspireDeployment] azd server API should be able to run asynchronously

### ISSUE THREAD

**Issue by abpiskunov** [Azure/azure-dev#3309] opened 2024-02-07 21:03 UTC
Now, when we are calling azd server from VS UX, any api could be called at any time triggered by the fact that user can click on different gestures why previous is loading. Currently any API we call from server would wait for completion of previous api calls which results in weird experience.

**Comment by weikanglim** [comment] 2024-02-07 23:18
Duplicate of #3287

**Closed by weikanglim** 2024-02-07 23:18 UTC
Labels: vs, aspire
