### ISSUE TITLE
Limit list of possible deploy locations based on service

### ISSUE THREAD

**Issue by GeekTrainer** [Azure/azure-dev#374] opened 2022-01-10 22:37 UTC
**Describe the bug**

Certain services, such as Azure Static Web Apps, are only available in a subset of regions. When using `azd provision` the full list of Azure regions is displayed.

**To Reproduce**

1. Create a template which uses a service available in a subset of regions
2. Run `azd provision`
3. The full list of regions is displayed

**Expected behavior**

When running `azd provision`, only the valid regions should display.

**Environment**

N/A

**Additional context**

I'd add it might be worthwhile considering having a reduced list of regions regardless of the service. The list of available regions is quite long, and can require a fair bit of scrolling to find the right one.

**Comment by rajeshkamal5050** [comment] 2023-09-20 05:08
Seems duplicate of #2695 which is fixed now by azd handling `allowed` decorator.

**Closed by rajeshkamal5050** 2023-09-20 05:08 UTC
Labels: cli
