### ISSUE TITLE
[Issue] unexpected bicep type: 'securestring'

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#1598] opened 2023-02-22 04:33 UTC
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 0.6.0-beta.2 (commit c4a201e55a13eba77f9037b296a90e0f81b00dbe)

**Describe the bug**

When I try to deploy my ACA app, I get this output:

```
  |   ====| Creating a deployment planpanic: unexpected bicep type: 'securestring'

goroutine 66 [running]:
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).mapBicepTypeToInterfaceType(0x48dd480?, {0xc00019e810?, 0xc})
	/Users/runner/work/1/s/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:747 +0x228
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).ensureParameters(0xc000512800, {0x4b70fd8, 0xc0005438f0}, 0x8?, {{0xc0000aa060, 0x5b}, {0xc00019e770, 0x7}, 0xc000543d40, 0xc0004c0750}, ...)
	/Users/runner/work/1/s/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:949 +0x695
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).Plan.func1(0xc00051e000)
	/Users/runner/work/1/s/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:145 +0x3cd
github.com/azure/azure-dev/cli/azd/pkg/async.(*InteractiveTaskWithProgress[...]).Run.func1()
	/Users/runner/work/1/s/cli/azd/pkg/async/task.go:191 +0x1a8
created by github.com/azure/azure-dev/cli/azd/pkg/async.(*InteractiveTaskWithProgress[...]).Run
	/Users/runner/work/1/s/cli/azd/pkg/async/task.go:186 +0x1cb
```

I see the code in azure-dev which probably needs updating to include 'securestring', but I wonder if there's a deeper issue, since my Bicep files don't implicitly use securestring anywhere.

**To Reproduce**

git checkout https://github.com/pamelafox/flask-surveys-container-app
azd up

**Expected behavior**

I expected it to deploy, as it has in the past.

**Environment**

Terminal app, Mac M1 Pro, Ventura

cc @weikanglim as we were discussing this in Teams

**Comment by rajeshkamal5050** [comment] 2023-02-22 06:44
Suspecting you have a Bicep version >= https://github.com/Azure/bicep/releases/tag/v0.14.6 and running into issue https://github.com/Azure/bicep/issues/9224 caused by the M1 arm64 binary bits provided for dev testing.

Remove your current bicep from here ~/.azd/bin/bicep and try provision again. It should download Bicep 0.12.40 corresponding to 0.6.0-beta.2 and provision should work fine.

```
~/.azd/bin/bicep --version
Bicep CLI version 0.12.40 (41892bd0fb)
```

**Comment by pamelafox** [comment] 2023-02-22 16:03
Aha, that fixed it, thanks!

**Comment by rajeshkamal5050** [comment] 2023-02-23 03:52
Closing this for now. Since it was caused due to playing with the latest ARM bits and its new Bicep.

**Closed by rajeshkamal5050** 2023-02-23 03:52 UTC
Labels: area/bicep, area/provisioning
