### ISSUE TITLE
Provide `azd init` flag to "Use Code in Current Directory" without having to prompt user

### ISSUE THREAD

**Issue by stuartpa** [Azure/azure-dev#3339] opened 2024-02-12 14:56 UTC
We want to be able to run `azd init` without it requiring user input.

@ellismg has the context.

**Comment by weikanglim** [comment] 2024-03-21 03:05
I'm closing this as duplicate of #3361 based on the title. However, I suspect that the scenario is to fully run `azd init` without any prompts. We can continue that discussion on #3341.

**Closed by weikanglim** 2024-03-21 03:05 UTC
Labels: enhancement, easy-init
