### ISSUE TITLE
[Issue] Login token expires while executing in a GitHub Action workflow in the azd container.

### ISSUE THREAD

**Issue by sabbour** [Azure/azure-dev#1901] opened 2023-04-07 07:27 UTC
**Version:** Container image using the `:daily` tag.
**Environment:** GitHub Actions workflow

While running a GitHub Action workflow, the `azd provision` step takes about 11 minutes. By the time it is completed, trying to execute `azd deploy` results in an error message:  `ERROR: getting target resource: getting service resource: not logged in, run 'azd auth login' to login`.

My assumption is that the OIDC token expires and that this is a similar bug to https://github.com/Azure/login/issues/180 that the Azure/login action faces. 

My workaround is to issue another `azd login` action before running `azd deploy` but it is confusing and cumbersome.

**See non-working pipeline run:** https://github.com/sabbour/contoso-names-e2e/actions/runs/4636146397/jobs/8203775220
**See working pipeline with the extra logins run:** https://github.com/sabbour/contoso-names-e2e/actions/runs/4636235684/jobs/8203944300

Running the same locally using `azd provision` followed by `azd deploy` doesn't not reproduce the issue. This is specific to the GitHub Actions and/or running the Azure Developer CLI container.

**Comment by sabbour** [comment] 2023-04-07 07:33
Related to https://github.com/Azure/azure-dev/issues/1653

**Comment by sabbour** [comment] 2023-04-07 21:24
Duplicate of: https://github.com/Azure/azure-dev/issues/1740

**Comment by weikanglim** [comment] 2023-04-07 23:31
@sabbour This is a really good find! Appreciate the write-up.

Took a quick look, and I can confirm the current implementation seems to be fetching the token during login, persisting the token:

https://github.com/Azure/azure-dev/blob/9cbad62811cbae78f18698253e126e7ee3a8526d/cli/azd/pkg/auth/manager.go#L443-L478

And reusing the stored token instead of providing a callback that allows for token exchange:

https://github.com/Azure/azure-dev/blob/9cbad62811cbae78f18698253e126e7ee3a8526d/cli/azd/pkg/auth/manager.go#L209-L210

**Comment by rajeshkamal5050** [comment] 2023-04-12 21:47
@weikanglim  Not sure if its the same as the OIDC login timeout issue as part of pipelines. Any findings in this?

**Comment by weikanglim** [comment] 2023-04-13 00:26
@rajeshkamal5050 It is the same. The findings are above. Took a second look at the code, it's a simple change. I'm going to assign it to myself.

**Closed** 2023-04-17 23:27 UTC
Labels: bug, blocker, cli

**Comment by justinmchase** [comment] 2024-01-25 00:57
So does one just call `az login` in a script somewhere and it will refresh the credentials? Or how does one solve this issue?

**Comment by weikanglim** [comment] 2024-01-29 17:18
Hi @justinmchase , not sure about your use case, but the idea behind this change: 

1. GitHub Actions integrates with Azure to offer federated credentials.
2. Federated credentials can be retrieved by using environment variables on the runner (ACTIONS_ID_TOKEN_REQUEST_URL and ACTIONS_ID_TOKEN_REQUEST_TOKEN), described in [GitHub docs](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers). The access token should be retrieved by querying ACTIONS_ID_TOKEN_REQUEST_URL using ACTIONS_ID_TOKEN_REQUEST_TOKEN. For a reference implementation, see a simplified implementation I made for a CLI project of mine: [kusto-synced](https://github.com/weikanglim/kusto-synced/blob/0816a1b01fcdaa7417f966ec5f2340bb785e69a6/internal/ksd/client.go#L159).

If you're using `azd` or `az` to fetch the configured credentials, the CLI should handle this for you.

**Comment by justinmchase** [comment] 2024-01-29 18:36
It is definitely timing out and not handling it.

My use case is I use the azure login action, az cli works fine, then I run a very long running terraform apply and inside of that terraform apply I have some external resources that invoke bash scripts to do things the azurerm provider can do or doesn't do right and I have to invoke the az cli, which throws an expired token error.

If I use that snippet to first refresh the oidc token all is well again but the az cli is definitely not doing it automatically.

**Comment by weikanglim** [comment] 2024-01-29 22:17
@justinmchase I see. It's possible that `az` handles this differently than `azd`, as described in this [az comment](https://github.com/Azure/login/issues/372#issuecomment-1871874376). I'm not familiar with the az implementation, so we'll definitely need to work with the Azure CLI folks at [Azure/login](https://github.com/Azure/login). I see that you've commented on the issue here: https://github.com/Azure/login/issues/180#issuecomment-1545459942. Can you add a workflow that reproduces the issue to https://github.com/Azure/login/issues/372 so that the team can better take a look at it? We should continue discussion there since it's `az` related.

**Comment by justinmchase** [comment] 2024-01-30 02:48
Ok, I guess I thought azd was a debug build of az. I'll follow up over there I can probably reproduce by simply adding a sleep step. I'll try it out thanks.

**Comment by cforce** [comment] 2024-02-06 15:26
Same issue here. Unable to use federated token's provided by Azure in azd inside a container. Seems like the "az  login" done via federated token can't be reused by  azd . Please support oidc token reuse from az cli or allow to use azd not only with for provider github but any idp supporting oidc
