### ISSUE TITLE
[WebToolsE2E][Aspire] Running 'azd init' failed wth error 'ERROR: unsupported resource type: sqlserver.database.v1' after adding sql server related aspire component

### ISSUE THREAD

**Issue by v-cazhang** [Azure/azure-dev#3140] opened 2023-12-19 10:42 UTC
**REGRESSION INFO**: Also repro on VS 17.9 P2 (includes Aspire 8.0.0-preview.1.23557.2) + azd 1.5.0

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.9 Preview 2
3. Install Aspire Preview 2 latest build 8.0.0-preview.2.23618.4
4. Apply NuGet Feeds
5. Install azd 1.5.1-daily.3351945

**REPRO STEPS**

1.  In the VS, create a new project > ASP.NET Core Web App > .NET 8.0 > Individual Accounts > Create.
2. Right-click the web project >Add > Aspire component > check 'Include prerelease' and set 'Package resource' to 'All' > Aspire.Microsoft.EntityFrameworkCore.SqlServer > install with matched version
5. Open appsettings.json of web project, make changes related to Aspire component
```
{
  "Aspire": {
    "Microsoft": {
      "EntityFrameworkCore": {
        "SqlServer": {
          "DbContextPooling": true,
          "HealthChecks": false,
          "Tracing": false,
          "Metrics": true
        }
      }
    }
  }
}
```
6. In the Program.cs of web project, comment the DbContext register line, type following codes: 
`builder.AddSqlServerDbContext<MyDbContext>("myConnection"); `
7. Open appsettings.json of AppHost project, add ConnectionStrings configuration section: 
```
{ 
  "ConnectionStrings": { 
    "myConnection": "Data Source=myserver;Initial Catalog=master" 
  } 
} 
```
8.Open Program.cs of AppHost project, add following codes: 
```
var sql = builder.AddSqlServerContainer("sql").AddDatabase("sqldata");
var myService = builder.AddProject<Projects.MyService>()
                       .WithReference(sql); 
```
9. Right-click the solution > Open Folder in File Explorer, in the opened folder, right-click any place > Open in Terminal
10. In the terminal window, running 'azd init', select 'Use code in the current directory' > 'Confirm and continue initializing my app' > select all the services > enter a new environment name > press enter.

**Notes**:

1. This issue also repro after adding 'Aspire.Microsoft.Data.SqlClient'.

**ACTUAL**
Shows error 'ERROR: unsupported resource type: sqlserver.database.v1'
![image](https://github.com/Azure/azure-dev/assets/82028229/732ad281-b589-4529-b9f8-71b0fc722659)

**EXPECTED**
Running 'azd init' successfully.

**Comment by rajeshkamal5050** [comment] 2023-12-21 06:46
We don't have support for `sqlserver` yet. Duplicate of existing issue.
- https://github.com/Azure/azure-dev/issues/3065

**Closed by rajeshkamal5050** 2023-12-21 06:46 UTC
Labels: question, customer-reported, aspire
