### ISSUE TITLE
Azure Dev Provision failed for todo-java-postgresql-terraform in Azure DevOps

### ISSUE THREAD

**Issue by blow-hey** [Azure/azure-dev#2230] opened 2023-05-16 10:25 UTC
**Describe the issue:**
Azure DevOps pipeline test failed when run `azd pipeline config --provider azdo`

The error message as follows:
![image](https://github.com/Azure/azure-dev/assets/112381413/866d2c0c-6f22-4d83-a6b5-e9131f357d84)

**Repro steps:**

1. Run `azd auth login`
2. Run `azd init -t todo-java-postgresql-terraform`
3. Run `azd pipeline config --provider azdo`

**Environment:**
OS: Windows desktop, MacOS desktop, Linux desktop, WSL, DevContainer in VS Code.
Template: https://github.com/Azure-Samples/todo-java-postgresql-terraform
Azd version: 0.9.0-beta.2-daily.2772915 (commit https://github.com/Azure/azure-dev/commit/08ff66607eb70b25d189aefce0d21070fe84630d)

**Expected behavior:**
Run command `azd pipeline config --provider azdo` success.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment] 2023-05-16 16:31
The deployment error seems to be a duplicate of #2233 issues 1st part.

**Closed by rajeshkamal5050** 2023-05-16 16:31 UTC
Labels: needs-triage

**Comment by v-jiaodi** [comment] 2023-06-14 09:27
@rajeshkamal5050 This issue can be reproduced when running the command `azd pipeline config --provider azdo`.

**Environment:**


- OS: Windows desktop, MacOS desktop, Linux desktop, WSL and Devcontainer in VS Code.
- Template: todo-java-postgresql-terraform
- Branch: staging
- Azd version: azd version 1.1.0-beta.1-daily.2845223 (commit https://github.com/Azure/azure-dev/commit/9e11674b30a1b0c456fbd8a042d6f5af77ec6188)
