### ISSUE TITLE
Deployment is not valid according to the validation procedure in todo-nodejs-mongo-swa-func.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-dev#496] opened 2022-08-19 09:41 UTC
**Describe the issue:**
Deploy failed when we try to run the file: "test-templates".

**Repro Steps:**
1. Click **Reopen in container** with vscode.
2. Run `bash ./test-templates.sh -t todo-nodejs-mongo-swa-func -b pr/471 -e tnmsf -c false` in container.

**Error Message:**
![image](https://user-images.githubusercontent.com/81678720/185589635-98b645fa-5387-41f6-84ff-5f5c41dd5f7b.png)

**Environment:**
devcontainer
Template: https://github.com/azure-samples/todo-nodejs-mongo-swa-func  
Based on: https://github.com/Azure/azure-dev/pull/471

**Expected behavior:**
Create resource with the command:  `bash ./test-templates.sh -t tode-nodejs-mongo-swa-func -b pr/471 -e tnmsf -c false` can success.

@jongio , @savannahostrowski for notification.

**Comment by rajeshkamal5050** [comment] 2022-08-23 07:04
@zedy-wj can you check again? Is this related to
- https://github.com/Azure/azure-dev/issues/497

**Comment by zedy-wj** [comment] 2022-08-23 08:25
@rajeshkamal5050 - This issue is no longer reproduced. It happens during deployment and it has nothing to do with the #497.

**Comment by zedy-wj** [comment] 2022-08-24 03:27
@jongio - This issue doesn't reproduce anymore, do you know which pr fixed it?

**Comment by rajeshkamal5050** [comment] 2022-08-24 18:53
Closing this issue for now. Since it is not reproducible. @jongio if you know, please reference the PR which fixed it.

**Closed by rajeshkamal5050** 2022-08-24 18:53 UTC
Labels: templates
