### ISSUE TITLE
[WebToolsE2E][Aspire] Deploying Aspire-Samples/Metrics solution using 'azd up', the status of container app shows failed: ContainerCrashing

### ISSUE THREAD

**Issue by v-cazhang** [Azure/azure-dev#3321] opened 2024-02-08 08:41 UTC
**REGRESSION INFO**: Also repro on Aspire 8.0.0-preview.2.23619.3

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1 [latest build, includes Aspire 8.0.0-preview.3.24105.21 ]
3. Apply NuGet Feeds
4. Install Docker Desktop for Windows

**REPRO STEPS**
1. Clone aspire-samples repo from preview.3 branch
2. Update NuGet.config to use the correct feeds
3. Open samples\Metrics.sln
4. Build
5. Right-click solution > Open Folder in File Explorer. In the opened folder, click any place > Open in Terminal
6. Runing 'azd init', select 'Use code in the current directory' > Confirm and continue initializing my app, type a new environment name, press enter.
7. When running azd init choose to expose 'app' to the Internet
8. Run azd up to deploy to Azure
9. Open the resource group, click the 'app' container app.

**ACTUAL**:
The status shows failed: Failed:appContainerCrashing:
![image](https://github.com/Azure/azure-dev/assets/82028229/9a91251d-e1eb-4ab6-84cb-1d9d4ea4a2e1)

**EXPECTED**
No issues
![image](https://github.com/Azure/azure-dev/assets/82028229/81e71122-8849-409a-ab48-9e36df21730c)

**Comment by rajeshkamal5050** [comment] 2024-02-08 17:34
@vhvb1989 can you try this?

**Comment by davidfowl** [comment] 2024-02-08 18:11
I don’t think this is a new problem. We don’t have a way to represent volumes in the manifest and this sample relies on them

**Comment by v-sherryfan** [comment] 2024-02-21 09:20
This issue also reproduce on samples\AspireWithDapr.sln solution.

**Comment by davidfowl** [comment] 2024-02-21 09:30
@v-sherryfan can you paste the output of streaming logs here?

**Comment by v-sherryfan** [comment] 2024-02-21 10:06
@davidfowl The log stream is as below:

2024-02-21T10:01:44.10957  Connecting to the container 'webfrontend'...

2024-02-21T10:01:44.13786  Successfully Connected to container: 'webfrontend' [Revision: 'webfrontend--p5ywlwb-7c6b8ccf77-lwln2', Replica: 'webfrontend--p5ywlwb']
2024-02-21T09:59:40.228555288Z Unhandled exception. System.InvalidOperationException: This service descriptor is keyed. Your service provider may not support keyed services.
2024-02-21T09:59:40.228591636Z    at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.ThrowKeyedDescriptor()
2024-02-21T09:59:40.228595493Z    at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.get_ImplementationType()
2024-02-21T09:59:40.228598849Z    at Microsoft.Extensions.DependencyInjection.DaprServiceCollectionExtensions.<>c.<AddDaprClient>b__0_0(ServiceDescriptor s)
2024-02-21T09:59:40.228602035Z    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
2024-02-21T09:59:40.228604961Z    at Microsoft.Extensions.DependencyInjection.DaprServiceCollectionExtensions.AddDaprClient(IServiceCollection services, Action`1 configure)
2024-02-21T09:59:40.228608577Z    at Program.<Main>$(String[] args) in C:\Users\v-sherryfan\source\repos\aspire-samples\samples\AspireWithDapr\AspireWithDapr.Web\Program.cs:line 13

**Comment by vhvb1989** [comment] 2024-02-26 23:22
The sample from https://github.com/dotnet/aspire-samples/tree/main/samples/AspireWithDapr might be out of date for preview4.

The code and API looks different from the one at https://github.com/dotnet/aspire/tree/main/playground/dapr

@philliphoff , are you keeping both samples?  Do you know which one is the right one?   Should we keep just one?

**Comment by vhvb1989** [comment] 2024-02-26 23:42
Root caused to: https://github.com/dapr/dotnet-sdk/issues/1235

There is a workaround to use version `1.13.0-rc03` for the dapr samples.  I'm closing this as not-azd related.

**Closed by vhvb1989** 2024-02-26 23:42 UTC
Labels: question, customer-reported, aspire

**Comment by vhvb1989** [comment] 2024-02-26 23:45
@v-cazhang for any future `container crashing`, can we have a new/unique issue please?

Let's avoid combining issues from different samples.  The `container crashing` could be happening for a lot of reasons, so it is better to have unique issues with the logstream from the container

**Comment by v-cazhang** [comment] 2024-02-27 01:54
> @v-cazhang for any future `container crashing`, can we have a new/unique issue please?
> 
> Let's avoid combining issues from different samples. The `container crashing` could be happening for a lot of reasons, so it is better to have unique issues with the logstream from the container

Got it, we will open separate issue for any `container crashing` in the future.

**Comment by v-sherryfan** [comment] 2024-02-29 09:12
This issue is not reproduced on Aspire 8.0 P3 and 8.0 P4 after updating 'Dapr.AspNetCore' version to 1.13.0-rc03.
