### ISSUE TITLE
[Issue] Get deployment error detail that doesn't map to bicep files

### ISSUE THREAD

**Issue by dfberry** [Azure/azure-dev#3195] opened 2024-01-12 20:28 UTC
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 1.5.1 (commit 3856d1e98281683b8d112e222c0a7c7b3e148e96)

**Describe the bug**
Error after all resources provisioned. I _believe_ the error is a false positive for something else happening. 

```
   GET https://management.azure.com/subscriptions/19016922-4bf5-4c41-9553-8eff5da1500e/providers/Microsoft.Resources/deployments/dfberry-20240112-06-1705089354/operationStatuses/08584965175277940942?api-version=2021-04-01
   Authorization: REDACTED
   User-Agent: azsdk-go-armresources/v1.0.0 (go1.21.0 X:loopvar; linux),azdev/1.5.1 (Go go1.21.0 X:loopvar; linux/amd64)
   X-Ms-Correlation-Request-Id: a406082f23b20e658adcc54dc14d1e30
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Cache-Control: no-cache
   Content-Type: application/json; charset=utf-8
   Date: Fri, 12 Jan 2024 19:57:59 GMT
   Expires: -1
   Pragma: no-cache
   Strict-Transport-Security: REDACTED
   Vary: REDACTED
   X-Content-Type-Options: REDACTED
   X-Ms-Correlation-Request-Id: a406082f23b20e658adcc54dc14d1e30
   X-Ms-Ratelimit-Remaining-Subscription-Reads: REDACTED
   X-Ms-Request-Id: 4f6968dc-f14b-45cb-92a8-07ec80e8c3ef
   X-Ms-Routing-Request-Id: REDACTED

2024/01/12 19:57:59 main.go:48: Retry: response 200
2024/01/12 19:57:59 main.go:48: Retry: exit due to non-retriable status code
2024/01/12 19:57:59 main.go:48: LongRunningOperation: State Failed
2024/01/12 19:57:59 main.go:48: LongRunningOperation: END PollUntilDone() for *async.Poller[github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources.DeploymentsClientCreateOrUpdateAtSubscriptionScopeResponse]: succeeded, total time: 2m0.761906653s

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
DeploymentNotFound: Deployment 'api' could not be found.

TraceID: a406082f23b20e658adcc54dc14d1e30
```

**To Reproduce**
1. Open [branch](https://github.com/dfberry/todo-nodejs-mongo-aca/tree/diberry/separate-infra) in Codespaces
2. `azd auth login`
3. `azd provision --debug` - default provisions just main.bicep and nothing from api or web
4. Azure portal doesn't show any errors in deployment logs

![image](https://github.com/Azure/azure-dev/assets/1517008/1c5b21c7-885e-4ae7-abd0-1916783e013b)

**Expected behavior**
If the provision fails with an error - some way to figure out what the issue is. Since this is strictly a provision, is the term `deployment` in the error just about azure deployment logs, or is there something about the main.bicep conditional provisioning based on the `provisionAll` param. 

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3] - Codespaces in browser

**Additional context**
@jongio Helped me change the infra from provision all in one shot to separate base, api, and web deployments. Perhaps there is some error in bicep for that separation I don't see?

**Comment by rajeshkamal5050** [comment] 2024-01-17 18:41
@dfberry was the `DeploymentNotFound` transient?

@v-xuto can you try reproducing this?

**Comment by zedy-wj** [comment] 2024-01-18 07:07
@rajeshkamal5050 , @dfberry - We can reproduce this error, but I think this is expected. 

Because the condition deployment `if(provisionAll)` was added when creating the `api` and `web` modules.

![image](https://github.com/Azure/azure-dev/assets/81678720/8ef00afe-0b59-4f9a-93d6-828ed306d922)

And the boolean value `provisionAll` was set to `false` by default.
![image](https://github.com/Azure/azure-dev/assets/81678720/9eccc807-738f-4067-b253-bfefb81ffc70)

Therefore, this error actually occurs when referencing the `api` module in the `web` module.
![image](https://github.com/Azure/azure-dev/assets/81678720/fcd2c400-3050-476f-87ef-d4a717bf84fd)

If you use a [reference](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-resource#reference) or [list](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-resource#list) function with a resource that is conditionally deployed, the function is evaluated even if the resource isn't deployed. You get an error if the function refers to a resource that doesn't exist. For specific information, please refer to the document [here](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/conditional-resource-deployment#runtime-functions).


Quick workaround, can be changed as follows:
![image](https://github.com/Azure/azure-dev/assets/81678720/1a99b952-76c8-485e-b2a2-53abdac288e9)

**Comment by weikanglim** [comment] 2024-06-19 21:36
Closing since the workaround was provided above for the Bicep conditional deployment issue.

**Closed by weikanglim** 2024-06-19 21:36 UTC
Labels: bug, question, customer-reported, needs-team-attention, area/bicep, area/core-cli
