### ISSUE TITLE
[codespaces] Python extension not installed by default even when configured in devcontainer.json

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#923] opened 2022-10-19 18:12 UTC
When attempting to debug a python app: 

![image](https://user-images.githubusercontent.com/2158838/196771067-9f87e53b-ea3e-4b3a-bba6-90ed04ec357f.png)

The `devcontainer.json` file contains an entry for the Python extension ([example](https://github.com/Azure-Samples/todo-python-mongo-swa-func/blob/main/.devcontainer/devcontainer.json#L24))

Yet the interface reports that the extension is not installed: 

![image](https://user-images.githubusercontent.com/2158838/196771339-08edf579-2d4f-4065-ab4e-d3c8c303fcce.png)

**Comment by danieljurek** [comment] 2022-10-19 18:19
Rebuilding the container appears to have helped on this one. Is there a way to make sure the requisite extensions are installed?

**Comment by weikanglim** [comment] 2022-11-02 23:03
We do specify prereq extensions in `devcontainer.json`. Closing out as i was unable to reproduce this.

**Closed by weikanglim** 2022-11-02 23:03 UTC
Labels: codespaces
