### ISSUE TITLE
[Issue] panic: runtime error: invalid memory address or nil pointer dereference when use WithServiceBinding with env

### ISSUE THREAD

**Issue by KSemenenko** [Azure/azure-dev#3154] opened 2023-12-20 22:13 UTC
and 1.5.1

aspire preview2
```cs
var silo = builder.AddProject<Projects.Silo>("silo")
     .WithServiceBinding(8080, "http")
     .WithServiceBinding(11111, "http", env:"PORT1")
     .WithServiceBinding(30000, "http", env: "PORT2");
```

Crash
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102d7fb10]

goroutine 1 [running]:
github.com/azure/azure-dev/cli/azd/pkg/apphost.infraGenerator.evalBindingRef({0x1400061da10, 0x1400061da40, 0x1400061da70, 0x1400061daa0, 0x1400061dad0, 0x1400061db00, 0x1400061db60, {0x1, 0x1, 0x0, ...}, ...}, ...)
        /Users/runner/work/1/s/cli/azd/pkg/apphost/generate.go:848 +0x7f0
github.com/azure/azure-dev/cli/azd/pkg/apphost.(*infraGenerator).buildEnvBlock.func1({0x140006162a1?, 0x1027d3c24?})
        /Users/runner/work/1/s/cli/azd/pkg/apphost/generate.go:922 +0x70
github.com/azure/azure-dev/cli/azd/pkg/apphost.evalString({0x140006162a0, 0x21}, 0x140005bdeb8)
        /Users/runner/work/1/s/cli/azd/pkg/apphost/eval.go:29 +0x374
github.com/azure/azure-dev/cli/azd/pkg/apphost.(*infraGenerator).buildEnvBlock(0x140005be4a8, 0x102d7b864?, 0x140005be0b0)
        /Users/runner/work/1/s/cli/azd/pkg/apphost/generate.go:922 +0xa4
github.com/azure/azure-dev/cli/azd/pkg/apphost.(*infraGenerator).Compile(0x140005be4a8)
        /Users/runner/work/1/s/cli/azd/pkg/apphost/generate.go:731 +0x65c
github.com/azure/azure-dev/cli/azd/pkg/apphost.BicepTemplate(0x14000452000?)
        /Users/runner/work/1/s/cli/azd/pkg/apphost/generate.go:118 +0x140
github.com/azure/azure-dev/cli/azd/pkg/project.(*DotNetImporter).SynthAllInfrastructure(0x140005beb88?, {0x10353c188?, 0x14000032c30?}, 0x14000149810, 0x2?)
        /Users/runner/work/1/s/cli/azd/pkg/project/dotnet_importer.go:238 +0xf4
github.com/azure/azure-dev/cli/azd/pkg/project.(*ImportManager).SynthAllInfrastructure(0x14000118088, {0x10353c188, 0x14000032c30}, 0x14000149810)
        /Users/runner/work/1/s/cli/azd/pkg/project/importer.go:144 +0x104
github.com/azure/azure-dev/cli/azd/cmd.(*infraSynthAction).Run(0x140006941c0, {0x10353c188, 0x14000032c30})
        /Users/runner/work/1/s/cli/azd/cmd/infra_synth.go:96 +0xd4
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x10353c188?, 0x14000032c30?})
        /Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:127 +0x258
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*TelemetryMiddleware).Run(0x14000690710, {0x10353c188, 0x140004fab70}, 0x14000694200)
        /Users/runner/work/1/s/cli/azd/cmd/middleware/telemetry.go:85 +0x6f4
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x10353c188, 0x140004fab70})
        /Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:125 +0x20c
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*ExperimentationMiddleware).Run(0x10307d1fd?, {0x10353c188, 0x140004fab70}, 0x14000694200)
        /Users/runner/work/1/s/cli/azd/cmd/middleware/experimentation.go:64 +0x338
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x10353c188, 0x140004fab70})
        /Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:125 +0x20c
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*DebugMiddleware).Run(0x1400000e228, {0x10353c188, 0x140004fab70}, 0x14000694200)
        /Users/runner/work/1/s/cli/azd/cmd/middleware/debug.go:48 +0x30c
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x10353c188, 0x140004fab70})
        /Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:125 +0x20c
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction(0x14000477e30, {0x10353c188, 0x140004fab70}, 0x1032acfa0?, {0x103530898?, 0x140006941c0})
        /Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:131 +0x1e4
github.com/azure/azure-dev/cli/azd/cmd.(*CobraBuilder).configureActionResolver.func1(0x14000463b80, {0x103c08000?, 0x0, 0x0})
        /Users/runner/work/1/s/cli/azd/cmd/cobra_builder.go:142 +0x3a4
github.com/spf13/cobra.(*Command).execute(0x14000463b80, {0x103c08000, 0x0, 0x0})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x554
github.com/spf13/cobra.(*Command).ExecuteC(0x14000426a00)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x318
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(0x10353c150?, {0x10353c150?, 0x103c08000?})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:895 +0x48
main.main()
        /Users/runner/work/1/s/cli/azd/main.go:61 +0x1c4
ksemenenko@konstantins-macbook-pro Apps % azd infra synth

WARNING: Feature 'infraSynth' is in alpha stage.
To learn more about alpha features and their support, visit https://aka.ms/azd-feature-stages.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104ebfb10]

goroutine 1 [running]:
github.com/azure/azure-dev/cli/azd/pkg/apphost.infraGenerator.evalBindingRef({0x140003e4330, 0x140003e4360, 0x140003e4420, 0x140003e4450, 0x140003e4540, 0x140003e4570, 0x140003e4c30, {0x1, 0x1, 0x0, ...}, ...}, ...)
        /Users/runner/work/1/s/cli/azd/pkg/apphost/generate.go:848 +0x7f0
github.com/azure/azure-dev/cli/azd/pkg/apphost.(*infraGenerator).buildEnvBlock.func1({0x1400047e451?, 0x10491d36c?})
        /Users/runner/work/1/s/cli/azd/pkg/apphost/generate.go:922 +0x70
github.com/azure/azure-dev/cli/azd/pkg/apphost.evalString({0x1400047e450, 0x21}, 0x140005bdeb8)
        /Users/runner/work/1/s/cli/azd/pkg/apphost/eval.go:29 +0x374
github.com/azure/azure-dev/cli/azd/pkg/apphost.(*infraGenerator).buildEnvBlock(0x140005be4a8, 0x104ebb864?, 0x140005be0b0)
        /Users/runner/work/1/s/cli/azd/pkg/apphost/generate.go:922 +0xa4
github.com/azure/azure-dev/cli/azd/pkg/apphost.(*infraGenerator).Compile(0x140005be4a8)
        /Users/runner/work/1/s/cli/azd/pkg/apphost/generate.go:731 +0x65c
github.com/azure/azure-dev/cli/azd/pkg/apphost.BicepTemplate(0x14000480050?)
        /Users/runner/work/1/s/cli/azd/pkg/apphost/generate.go:118 +0x140
github.com/azure/azure-dev/cli/azd/pkg/project.(*DotNetImporter).SynthAllInfrastructure(0x140005beb88?, {0x10567c188?, 0x14000118ae0?}, 0x14000151810, 0x2?)
        /Users/runner/work/1/s/cli/azd/pkg/project/dotnet_importer.go:238 +0xf4
github.com/azure/azure-dev/cli/azd/pkg/project.(*ImportManager).SynthAllInfrastructure(0x14000120088, {0x10567c188, 0x14000118ae0}, 0x14000151810)
        /Users/runner/work/1/s/cli/azd/pkg/project/importer.go:144 +0x104
github.com/azure/azure-dev/cli/azd/cmd.(*infraSynthAction).Run(0x140003bc100, {0x10567c188, 0x14000118ae0})
        /Users/runner/work/1/s/cli/azd/cmd/infra_synth.go:96 +0xd4
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x10567c188?, 0x14000118ae0?})
        /Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:127 +0x258
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*TelemetryMiddleware).Run(0x140002b26d0, {0x10567c188, 0x1400049f7d0}, 0x140003bc140)
        /Users/runner/work/1/s/cli/azd/cmd/middleware/telemetry.go:85 +0x6f4
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x10567c188, 0x1400049f7d0})
        /Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:125 +0x20c
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*ExperimentationMiddleware).Run(0x1051bd1fd?, {0x10567c188, 0x1400049f7d0}, 0x140003bc140)
        /Users/runner/work/1/s/cli/azd/cmd/middleware/experimentation.go:64 +0x338
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x10567c188, 0x1400049f7d0})
        /Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:125 +0x20c
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*DebugMiddleware).Run(0x14000532228, {0x10567c188, 0x1400049f7d0}, 0x140003bc140)
        /Users/runner/work/1/s/cli/azd/cmd/middleware/debug.go:48 +0x30c
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction.func1({0x10567c188, 0x1400049f7d0})
        /Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:125 +0x20c
github.com/azure/azure-dev/cli/azd/cmd/middleware.(*MiddlewareRunner).RunAction(0x14000477e30, {0x10567c188, 0x1400049f7d0}, 0x1053ecfa0?, {0x105670898?, 0x140003bc100})
        /Users/runner/work/1/s/cli/azd/cmd/middleware/middleware.go:131 +0x1e4
github.com/azure/azure-dev/cli/azd/cmd.(*CobraBuilder).configureActionResolver.func1(0x14000463b80, {0x105d48000?, 0x0, 0x0})
        /Users/runner/work/1/s/cli/azd/cmd/cobra_builder.go:142 +0x3a4
github.com/spf13/cobra.(*Command).execute(0x14000463b80, {0x105d48000, 0x0, 0x0})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x554
github.com/spf13/cobra.(*Command).ExecuteC(0x14000432a00)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x318
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(0x10567c150?, {0x10567c150?, 0x105d48000?})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:895 +0x48
main.main()
        /Users/runner/work/1/s/cli/azd/main.go:61 +0x1c4
```

**Comment by rajeshkamal5050** [comment] 2023-12-21 06:21
Thanks for the issue @KSemenenko 

Can you share the complete app model defined in your AppHost project(Program.cs) or the aspire manifest [using dotnet command](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/manifest-format#generate-a-manifest) ?

@weikanglim @vhvb1989 @mitchdenny

**Comment by KSemenenko** [comment] 2023-12-21 07:35
this is my program.cs
```cs
var builder = DistributedApplication.CreateBuilder(args);

builder.AddAzureProvisioning();

var storage = builder.AddAzureStorage("storage");
var table = storage.AddTables("table");
var blob = storage.AddBlobs("blob");

var db = builder.AddPostgres("postgres")
     .AddDatabase("keyload-db");

var silo = builder.AddProject<Projects.Keyload_Silo>("silo")
     .WithReference(table)
     .WithReference(blob)
     .WithReference(db)
     .WithServiceBinding(8080, "http")
     .WithServiceBinding(11111, "http")
     .WithServiceBinding(30000, "http");

```
and then Im playing around WithServiceBinding

**Comment by vhvb1989** [comment] 2023-12-21 18:41
@KSemenenko , is `builder.AddAzureProvisioning();` a typo?

![image](https://github.com/Azure/azure-dev/assets/24213737/737d390c-97d1-4a54-a68f-c916775265b4)

I tried this:

```
dotnet new aspire-starter
```
Then I added the `package reference` to the appHost like:

```
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" Version="8.0.0-preview.2.23618.4" />
    <PackageReference Include="Aspire.Hosting.Azure" Version="8.0.0-preview.2.23618.4" />
  </ItemGroup>
```

Then I changed the code from the AppHost to be:

```csharp
var builder = DistributedApplication.CreateBuilder(args);

builder.AddAzureProvisioning();

var storage = builder.AddAzureStorage("storage");
var table = storage.AddTables("table");
var blob = storage.AddBlobs("blob");

var db = builder.AddPostgres("postgres")
     .AddDatabase("db");

var silo = builder.AddProject<Projects.asp_iss_3154_ApiService>("silo")
     .WithReference(table)
     .WithReference(blob)
     .WithReference(db)
     .WithServiceBinding(8080, "http")
     .WithServiceBinding(11111, "http")
     .WithServiceBinding(30000, "http");

// builder.AddProject<Projects.asp_iss_3154_Web>("webfrontend")
//     .WithReference(silo);

builder.Build().Run();
```

If I comment `builder.AddAzureProvisioning();`, the app works fine and I can run `azd infra synth`

**Comment by vhvb1989** [comment] 2023-12-21 18:47
Update.

When adding the `silo` as a reference to `web` project, I get this error from dotnet generating manifest:

```
ERROR: failed registering service hooks, failed getting services: importing services: generating app host manifest: generating app host manifest: dotnet run --publisher manifest on project '/home/vivazqu/workspace/build/asp-iss-3154/asp-iss-3154.AppHost/asp-iss-3154.AppHost.csproj' failed: exit code: 134, stdout: Building...
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.InvalidOperationException: Sequence contains more than one element
         at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
         at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
         at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
         at Aspire.Hosting.Publishing.ManifestPublishingContext.WriteServiceDiscoveryEnvironmentVariables(IResource resource) in /_/src/Aspire.Hosting/Publishing/ManifestPublishingContext.cs:line 142
```

The error goes away if I only use one `serviceBinging` for `http`, like

```csharp
var silo = builder.AddProject<Projects.asp_iss_3154_ApiService>("silo")
     .WithReference(table)
     .WithReference(blob)
     .WithReference(db)
     .WithServiceBinding(8080, "http");
    // .WithServiceBinding(11111, "http")
     //.WithServiceBinding(30000, "http");
```

@mitchdenny , do we support multiple http port bindings?

**Comment by KSemenenko** [comment] 2023-12-22 08:42
@vhvb1989 for `builder.AddAzureProvisioning()`
you have to add
```
<PackageReference Include="Aspire.Hosting.Azure.Provisioning" Version="8.0.0-preview.2.23619.3" />
```

**Comment by KSemenenko** [comment] 2023-12-22 08:44
Ideally i need something like this:
```
.WithServiceBinding(8080, "http");
.WithServiceBinding(11111, "tcp")
.WithServiceBinding(30000, "tcp");
```

also is thera a way to set like "internal" or "external" for Azure Continer Apps? now I hava to go to bicep and set it manualy.

containerApp.tmpl.yaml
``` yaml
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    ingress:
      external: true
      targetPort: 8080
      transport: http
      allowInsecure: true
    registries:
    - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
      identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
  template:
    containers:
    - image: {{ .Image }}
      name: keyload-silo
      env:
      - name: AZURE_CLIENT_ID
        value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
      - name: ConnectionStrings__blob
        value: '{{ .Env.SERVICE_BINDING_BLOB_ENDPOINT }}'
      - name: ConnectionStrings__keyload-db
        value: '{{ connectionString "keyload-db" }}'
      - name: ConnectionStrings__table
        value: '{{ .Env.SERVICE_BINDING_TABLE_ENDPOINT }}'
      - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
        value: "true"
      - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
        value: "true"
      ports:
        - port: 11111
        - port: 30000
        - port: 8080
    scale:
      minReplicas: 1
tags:
  azd-service-name: keyload-silo
  aspire-resource-name: keyload-silo
```

**Comment by rajeshkamal5050** [comment] 2024-02-06 07:27
Couple of asks here related to,
- https://github.com/Azure/azure-dev/issues/3267
- https://github.com/dotnet/aspire/issues/2099

Marking duplicate of the above ones.

**Closed by rajeshkamal5050** 2024-02-06 07:27 UTC
Labels: question, customer-reported, aspire
