### ISSUE TITLE
azd env new should accept positional argument for name

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1040] opened 2022-10-31 15:40 UTC
I expected this to work
![image](https://user-images.githubusercontent.com/2163001/199048332-fef952cb-b42f-43cc-bbd5-7883340f503a.png)

But it asks me for an environment name.

**Comment by vhvb1989** [comment] 2022-10-31 19:11
I think we need to use `-e` or `--environment-name`.

If we support positional arg here. What would it happen if we do `azd env new foo -e bar` ?

**Comment by weikanglim** [comment] 2022-11-07 20:57
Duplicate of #502

**Closed by weikanglim** 2022-11-07 20:57 UTC
Labels: needs-triage
