### ISSUE TITLE
[Feature Request] Please consider adding `azd env delete <name>`

### ISSUE THREAD

**Issue by IEvangelist** [Azure/azure-dev#2124] opened 2023-05-08 18:16 UTC
As a feature request, please consider adding:

```
azd env delete <name>
```

This would perform two primary actions:

- Delete the environment locally, i.e.; the `.azure/<name>`.
- Update the `.azure/config.json` accordingly.

**Comment by savannahostrowski** [comment] 2023-05-10 19:08
This is a duplicate of #937

**Closed by savannahostrowski** 2023-05-10 19:08 UTC
Labels: cli, command, feature
