### ISSUE TITLE
provider 'terraform' is alpha feature and it's not enabled with `todo-java-postgresql-terraform`

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#2232] opened 2023-05-16 10:37 UTC
**Describe the issue:**
When run `azd up`,  provider 'terraform' is alpha feature and it's not enabled, error message as follow:

![image](https://github.com/Azure/azure-dev/assets/80496810/69c04856-4d3c-456e-8eec-2806de01d462)

**Repro Steps:**
1. Run`azd auth login`
2. Run `azd init -t todo-java-postgresql-terraform -b staging`.
3. Run `azd up`

**Environment:**
- OS: Windows desktop, MacOS desktop, Linux desktop,  WSL , Devcontainer in VS Code.
- Template: todo-java-postgresql-terraform
- Branch: staging
- Azd version: 0.9.0-beta.2-daily.2772915  (commit https://github.com/Azure/azure-dev/commit/08ff66607eb70b25d189aefce0d21070fe84630d)

**Expected behavior:**
 Run `azd up` can pass for `todo-java-postgresql-terraform`

@rajeshkamal5050 for notification.

**Comment by savannahostrowski** [comment] 2023-05-16 15:26
This is expected behaviour as the feature is in alpha.

**Comment by savannahostrowski** [comment] 2023-05-16 15:27
If you ran that command and re-ran `azd up`, did everything work as expected?

**Comment by v-xuto** [comment] 2023-05-17 02:44
@savannahostrowski  After executing command `azd config set alpha.terraform on` according to the prompt, and then executing "azd up" is successful. But, if we use this method to solve this issue, it is recommended to add relevant hints in the Readme.

**Comment by savannahostrowski** [comment] 2023-05-17 05:32
We have a note in the READMEs that should be easier to find when the template updates go out on Thursday.

Each template that uses TF for IaC states

> Note: Terraform is in alpha mode. You need to enable it by running azd config set alpha.terraform on. Read more about alpha features.

I'll close this for now. We can re-open if it needs to be made clearer.

**Comment by v-xuto** [comment] 2023-05-18 02:51
@savannahostrowski The same issue occurs when command `azd pipeline config --provider github` is executed, please fix it. More details can be found in https://github.com/Azure/azure-dev/issues/2229.

**Comment by savannahostrowski** [comment] 2023-05-18 03:04
@rajeshkamal5050 I think we'll need to get someone to add a step to TF pipeline definitions to enable the feature

**Comment by rajeshkamal5050** [comment] 2023-05-18 15:56
> @rajeshkamal5050 I think we'll need to get someone to add a step to TF pipeline definitions to enable the feature

Isn't that defeating the purpose of it being under feature flag. Users wouldn't even know its under feature-flag/alpha since they can now do init and pipeline config? Shouldn't we just add to read me something like init, change and then run?

**Comment by savannahostrowski** [comment] 2023-05-18 16:01
I don't think that it's defeating the purpose but we probably want to at least denote that pipeline runs will fail unless the user adds a step to their GHA. I'm fine with pointing the user to do that but we need to add an additional note in the readme. Users shouldn't be blocked from using TF in CI/CD in they understand the implications.

**Comment by rajeshkamal5050** [comment] 2023-05-18 16:23
@vhvb1989 please take care of adding a note to all the TF readme's on this.

**Comment by savannahostrowski** [comment] 2023-05-18 16:25
@vhvb1989 Let's just add a note to the bullet under next steps.
![image](https://github.com/Azure/azure-dev/assets/8949415/44fafeb6-287a-483d-a1f2-58ff8a9b8bff)

**Comment by weikanglim** [comment] 2023-05-18 21:40
@savannahostrowski @rajeshkamal5050 

A quicker way for use in CI is probably to set the env var:
`AZD_ALPHA_ENABLE_TERRAFORM: true`

**Comment by v-xuto** [comment] 2023-05-19 09:42
@rajeshkamal5050 This issue can be reproduced when running the command `azd pipeline config --provider github` or `azd pipeline config --provider github --auth-type client-credentials` or `azd pipeline config --provider azdo`.

**Environment:**
OS: Windows desktop, MacOS desktop, Linux desktop, WSL ,CodeSpace and Devcontainer in VS Code.
Template: todo-java-postgresql-terraform
Branch: staging
Azd version: azd version 0.9.0-beta.2-daily.2786873 (commit de89effa931a89e8125e520e5bc3ff473f014fb5)

**Comment by v-jiaodi** [comment] 2023-06-14 09:27
@rajeshkamal5050 This issue can be reproduced when running the command `azd pipeline config --provider github or azd pipeline config --provider github --auth-type client-credentials`.

**Environment:**


- OS: Windows desktop, MacOS desktop, Linux desktop, WSL and Devcontainer in VS Code.
- Template: todo-java-postgresql-terraform
- Branch: staging
- Azd version: azd version 1.1.0-beta.1-daily.2845223 (commit https://github.com/Azure/azure-dev/commit/9e11674b30a1b0c456fbd8a042d6f5af77ec6188)

**Comment by vhvb1989** [comment] 2023-07-10 20:19
PRs created:
https://github.com/fangjian0423/todo-java-postgresql-terraform/pull/5
https://github.com/fangjian0423/todo-java-postgresql-aca-terraform/pull/3

**Comment by v-jiaodi** [comment] 2023-07-12 09:39
@rajeshkamal5050 This issue can be reproduced when running the command `azd pipeline config --provider github`.

**Environment:**


- OS: Windows desktop, MacOS desktop, Linux desktop, WSL and Devcontainer in VS Code.
- Template: todo-java-postgresql-terraform
- Branch: staging
- Azd version: azd version 1.0.3-beta.1-daily.2905893 (commit https://github.com/Azure/azure-dev/commit/a7126c9e3b8573d3874c47adf0caad927a551d76)

**Comment by v-xuto** [comment] 2023-08-08 07:23
This issue has been fixed. We will close this issue.

**Closed by v-xuto** 2023-08-08 07:23 UTC
Labels: templates, terraform, java
