### ISSUE TITLE
[feature] Support zip deploy to ASEv3 services

### ISSUE THREAD

**Issue by ayoussef-insight** [Azure/azure-dev#2136] opened 2023-05-09 01:36 UTC
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 0.8.0-beta.2 (commit 429b6ccf9a9d1616efa8988f2f8561deeb464c71)

**Describe the bug**
When deploying azure function app code to ASE hosted apps zipdeploy endpoints should use the ASE endpoint: e.g. *.scm.<ase_name>.appserviceenvironment.net.
azd only supports *.scm.azurewebsites.net endpoints which generates the following error when deploying to ASE hosted apps:

ERROR: failed deploying service 'funcapp': failing invoking action 'deploy', failed executing request: Post "https://<func_app>.scm.azurewebsites.net/api/zipdeploy?isAsync=true": dial tcp: lookup <func_app>.scm.azurewebsites.net on [fe80::18fa:b7ff:fef4:9f64%en0]:53: no such host

**To Reproduce**
- Prerequisites:
  - ASE v3 instance, windows app service plan (or linux) and azure function app hosted in the ASE plan 
  - Ensure you have access to a machine where you can connect to the ASE instance (e.g. a VM deploy to the same VNet)
  - Create an azd project and configure it to deploy an azure function code to the azure function resource hosted in the ASE.
- Steps: 
  - Run `azd deploy`

**Expected behavior**
azd should support a flag to allow deployments to ASE similar to [AzureFunctionApp@2](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v2?view=azure-pipelines)

**Environment**
    * .NET 6.0
    * Visual Studio Code

**Comment by rajeshkamal5050** [comment] 2023-05-09 15:52
@weikanglim can you triage this?

**Comment by weikanglim** [comment] 2023-05-09 23:20
Indeed, App Service Environment isn't currently supported. App Service Environment's doc on [endpoints](https://learn.microsoft.com/en-us/azure/app-service/environment/using#app-access) shows that we're not using the correct one.

**Comment by weikanglim** [comment] 2023-05-09 23:26
Closing this out as a dupe of #890 . Let's continue discussion there if needed.

**Closed by weikanglim** 2023-05-09 23:26 UTC
Labels: pm, feature, question, customer-reported, needs-team-attention, functions
