### ISSUE TITLE
"Azd init" failed for todo-java-postgresql-terraform on CodeSpace

### ISSUE THREAD

**Issue by blow-hey** [Azure/azure-dev#2231] opened 2023-05-16 10:25 UTC
**Describe the issue:**
Authentication failed for todo-java-postgresql-terraform when run `azd init`

The error message as follows:
![image](https://github.com/Azure/azure-dev/assets/112381413/52ca580d-70ef-44f9-a53c-0c8d3f3013e8)

**Repro steps:**

1. Run `azd auth login`
2. Run `azd init -t todo-java-postgresql-terraform`

**Environment:**
OS: CodeSpace in VS Code.
Template: https://github.com/Azure-Samples/todo-java-postgresql-terraform
Azd version: 0.9.0-beta.2-daily.2772915 (commit https://github.com/Azure/azure-dev/commit/08ff66607eb70b25d189aefce0d21070fe84630d)

**Expected behavior:**
Run command `azd init -t todo-java-postgresql-terraform` success.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment] 2023-05-16 16:15
@weikanglim @vhvb1989 

Adjusted https://github.com/Azure-Samples/todo-java-postgresql-terraform settings and made it similar to https://github.com/Azure-Samples/todo-python-mongo repo. The only difference should be private vs public.

Do you see anything else going on here?

@blow-hey can you re-try now?

**Comment by weikanglim** [comment] 2023-05-16 16:31
The error is happening because the template is private, and the user hasn't set up credentials for git auth.

To fix this,
```bash
# Press 'Y' when prompted about configuring git credentials
gh auth login

# Test this again to make sure 'git clone' works
cd <empty>
git clone https://github.com/Azure-Samples/todo-java-postgresql-terraform
```

Then rerun the template-tests command.

**Comment by Menghua1** [comment] 2023-05-17 03:23
@rajeshkamal5050  We have re-tried, we can't open the codespaces under this template by the following two methods now, please help resolve this issue.
![image](https://github.com/Azure/azure-dev/assets/111940661/ac593b5b-e84a-4507-9915-52b674db5897)

**Comment by v-xuto** [comment] 2023-05-19 09:48
@rajeshkamal5050 We can't open the codespaces under this template by the following two methods above.

**Environment:**
- OS: CodeSpace in VS Code
- Template: todo-java-postgresql-terraform
- Branch: staging
- Azd version: azd version 0.9.0-beta.2-daily.2786873 (commit https://github.com/Azure/azure-dev/commit/de89effa931a89e8125e520e5bc3ff473f014fb5)

**Comment by v-jiaodi** [comment] 2023-06-14 09:28
@rajeshkamal5050 This issue also occurs in the following cases:

- OS: CodeSpace.
- Template: todo-java-postgresql-terraform
- Branch: Staging
- Azd version: azd version 1.1.0-beta.1-daily.2845223 (commit https://github.com/Azure/azure-dev/commit/9e11674b30a1b0c456fbd8a042d6f5af77ec6188)

**Comment by v-jiaodi** [comment] 2023-07-12 09:41
@rajeshkamal5050 This issue also occurs in the following cases:

**Environment:**
- OS: CodeSpace.
- Template: todo-java-postgresql-terraform
- Branch: Staging
- Azd version: azd version 1.0.3-beta.1-daily.2905893 (commit https://github.com/Azure/azure-dev/commit/a7126c9e3b8573d3874c47adf0caad927a551d76)

**Comment by fangjian0423** [comment] 2023-07-18 08:02
This repo https://github.com/Azure-Samples/todo-java-postgresql-terraform is created by @danieljurek , could you set it to public? cc @rajeshkamal5050

**Comment by rajeshkamal5050** [comment] 2023-07-18 20:42
@fangjian0423 @yiliuTo before making the repo public and make it work for CodeSpaces. 
- Can we make adjustments to consume GHA action and Azd DevContainer features?
- Can we test and make sure it works fine? Since, it has been sometime its been added.

For any help with testing or making adjustments w.r.t to GHA action and Azd DevContainer feature. You can work with @v-xuto

**Comment by fangjian0423** [comment] 2023-07-19 08:52
sure, we will continue work on them @rajeshkamal5050

**Comment by fangjian0423** [comment] 2023-07-20 05:48
@v-xuto I created a PR https://github.com/Azure/azure-dev/pull/2556 to update java-postgresql template, could you please help to test it, thanks!

Before you test it, I have a question about all the terraform templates. I notice that https://github.com/Azure/azure-dev/pull/2034 disable basic auth, and the [pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2933684&view=logs&jobId=efa60ded-0edb-5d2d-3d59-1c9496e3a69c&j=efa60ded-0edb-5d2d-3d59-1c9496e3a69c) runs successful in my postgresql update PR, but the templates run failed in my local or GHA action. 

Did I miss something (When I remove the code of the PR, it runs successful)?

![image](https://github.com/Azure/azure-dev/assets/5254035/59ab389e-af6f-4975-857d-26ddcb2512c1)

**Comment by blow-hey** [comment] 2023-07-20 10:05
We run `azd up` without the above problems.

**Comment by blow-hey** [comment] 2023-07-20 10:12
@fangjian0423  We have run `azd up`, not reproduce the issue you described.

- azd version: `azd version 1.1.0 (commit ea9cb12575734ee6a5f99c4d415c1a51d6f32d3e)` and `azd version 1.1.1-daily.2929186 (commit 175a4da25e487529a5eceef3461d7cbdcfb2fdee)`
- Branch:  [PR#2556](https://github.com/Azure/azure-dev/pull/2556)
- Template: todo-java-postgresql-terraform

**Comment by fangjian0423** [comment] 2023-07-20 10:42
hi @vhvb1989 , did you know why I get the above error when I run `azd up` in my local.

**Comment by vhvb1989** [comment] 2023-07-20 16:51
@fangjian0423 , you need to make sure that `az` and `azd` are both using the same subscription/account.

Looking at the error you are getting, `az` is using the sub:
![image](https://github.com/Azure/azure-dev/assets/24213737/a0d82c55-2995-48ff-8249-be4e77ec47eb)

I don't recognize this sub-id.

Run `az account show` to see more about that subscription. (az sets the subscription/account when you log in).
Then run `az account set --subscription xxxxxx-xxxxxx-xxx`  to match the same sub that `azd` is using.  That should resolve this issue.

**Comment by fangjian0423** [comment] 2023-07-31 11:58
hi @v-xuto, any updates for the PR - https://github.com/Azure/azure-dev/pull/2556?

**Comment by zedy-wj** [comment] 2023-08-01 16:46
@fangjian0423 - Sorry for the delay, we have tested for PR #2556, the latest issue was shown as below when executing `azd pipeline config`:
<img width="443" alt="image" src="https://github.com/Azure/azure-dev/assets/81678720/edbdcefb-eca8-44d5-a083-96f34d8bb68b">
Besides, issues #2268 , #2233, #2478 are no longer reproduced.

**Comment by fangjian0423** [comment] 2023-08-02 05:38
@zedy-wj It seems all terraform templates have above basic auth issue after https://github.com/Azure/azure-dev/pull/2034 merged. @vhvb1989 could you please help to take a look?

**Comment by vhvb1989** [comment] 2023-08-02 16:55
> @fangjian0423 - Sorry for the delay, we have tested for PR #2556, the latest issue was shown as below when executing `azd pipeline config`: <img alt="image" width="443" src="https://user-images.githubusercontent.com/81678720/257581852-edbdcefb-eca8-44d5-a083-96f34d8bb68b.png"> Besides, issues #2268 , #2233, #2478 are no longer reproduced.

@zedy-wj @fangjian0423 , this error means that the `az` and `azd` are not using the same subscription.
We need to add this to the pipeline definition:

> az account set --subscription "$(SubscriptionId)" 

See: https://github.com/Azure/azure-dev/blob/main/eng/pipelines/templates/steps/template-test-run-job.yml#L123C15-L123C65

That's what we do for testing templates on CI.

I can add this line to the terraform templates from Azure-dev (https://github.com/Azure/azure-dev/blob/main/templates/common/.azdo/pipelines/terraform/azure-dev.yml), and @fangjian0423, cand you do this for the terraform templates out of azure-dev?

**Comment by vhvb1989** [comment] 2023-08-02 23:32
Created PR to fix the pipeline definition for Terraform/GitHub: https://github.com/Azure/azure-dev/pull/2584

@fangjian0423 , you will need to apply this changes to your terraform templates as well.

**Comment by fangjian0423** [comment] 2023-08-03 01:50
> I can add this line to the terraform templates from Azure-dev (https://github.com/Azure/azure-dev/blob/main/templates/common/.azdo/pipelines/terraform/azure-dev.yml), and @fangjian0423, cand you do this for the terraform templates out of azure-dev?

Thanks @vhvb1989 , we don't have any terraform templates out of azure-dev.

Could you pls help to apply the modifications on https://github.com/Azure/azure-dev/blob/main/templates/common/.github/workflows/java/terraform/azure-dev.yml in your PR, I think it is no need to create a new PR to fix this.

**Comment by vhvb1989** [comment] 2023-08-03 17:01
@fangjian0423 , I was referring these templates: https://github.com/fangjian0423?tab=repositories&q=terrafo&type=&language=&sort=

**Comment by fangjian0423** [comment] 2023-08-04 01:42
The AZD postgresql templates in my repositories will move to azure-dev repo:

- https://github.com/fangjian0423/todo-java-postgresql-terraform -> https://github.com/Azure-Samples/todo-java-postgresql-terraform
- https://github.com/fangjian0423/todo-java-postgresql-aca-terraform -> https://github.com/Azure-Samples/todo-java-postgresql-aca-terraform (will create a new PR to create this repository soon)

**Comment by fangjian0423** [comment] 2023-08-04 01:43
Let me close this issue because it has been resolved.

**Comment by v-xuto** [comment] 2023-08-04 02:38
> @rajeshkamal5050 We have re-tried, we can't open the codespaces under this template by the following two methods now, please help resolve this issue. ![image](https://user-images.githubusercontent.com/111940661/238822608-ac593b5b-e84a-4507-9915-52b674db5897.png)

@fangjian0423 In this issue, the quoted question has not been resolved. About template `todo-java-postgresql-terraform`, currently we can't open the codespaces. Please help review and resolve.

**Comment by vhvb1989** [comment] 2023-08-04 20:28
@v-xuto , I created this PR: https://github.com/Azure/azure-dev/pull/2597

This should push a new version for https://github.com/Azure-Samples/todo-java-postgresql-terraform (on stagging branch) which you can test

**Comment by vhvb1989** [comment] 2023-08-04 21:39
Next step is to make the template public. @danieljurek help is needed

**Comment by vhvb1989** [comment] 2023-08-07 22:59
Repo is now public and codespaces can be created from it

**Closed by vhvb1989** 2023-08-07 22:59 UTC
Labels: codespaces, terraform, java
