### ISSUE TITLE
Add C#, Azure SQL, SWA, Func App Todo App Template

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#315] opened 2022-06-01 17:48 UTC

**Comment by rajeshkamal5050** [comment] 2022-08-16 04:55
@wbreza do you think this is a duplicate of https://github.com/Azure/azure-dev/issues/450 which @karolz-ms is looking into for the current milestone?

**Comment by wbreza** [comment] 2022-09-07 00:12
@rajeshkamal5050  - Not a duplicate, just a variation of the template with SWA & function app support.

**Comment by jongio** [comment] 2022-10-25 13:20
We are going with #316 for this template.

**Closed by jongio** 2022-10-25 13:20 UTC
Labels: feature, templates

**Comment by savannahostrowski** [comment] 2022-10-26 21:32
Do we have a link to this repo yet?
