### ISSUE TITLE
Feature request - add template to existing project

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-dev#1056] opened 2022-11-01 04:56 UTC
I'm working on a project that already uses azd to manage the environment, and I'm adding a new component to the project.

This new component will bring in a database, container app backend and SWA frontend, all from an existing template.

While it's possible to manually copy in the Bicep files and update the `azure.yaml` to include these new services, I'd like a way to use azd to incorporate it, something like:

```bash
azd add --template https://github.com/...
```

This command would:

- Download the template from the provided location
- Update the `azure.yaml` with the new services that the template defines
- Provide guidance on how to add the new services to the `resources.bicep` file (or automatically add them, if that's possible)

After that is done, the standard `azd` commands for provisioning, deploying and environment refresh would work as expect.

**Comment by savannahostrowski** [comment] 2023-05-10 19:17
I think that this will be handled via some of the composability work we have scoped in a semester or two. Moving to Germanium

**Comment by rajeshkamal5050** [comment] 2024-03-12 07:03
Marking this as a duplicate of #2386

**Closed by rajeshkamal5050** 2024-03-12 07:03 UTC
Labels: feature
