### ISSUE TITLE
[Issue] Transient issue with deploying a container app to registry

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#1753] opened 2023-03-17 17:58 UTC
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

azd version 0.7.0-beta.1 (commit 9ce71659f7688d0dc3dda8b84e5accedca58cf01)

**Describe the bug**
Description of issue you're seeing...

I had previously successfully provisioned and deployed https://github.com/pamelafox/flask-surveys-container-app

Today, when running `azd up`, I got this error:

```
ERROR: deployment failed: error deploying infrastructure: failed deploying: deploying to subscription:

Deployment Error Details:
WebhookInvalidParameterValue: The following field(s) are either invalid or missing. Invalid value: "flasksurveysxvmcmelitbap4registry.azurecr.io/flask-surveys-container-app/web-flasksurveys:azdev-deploy-1675379805": GET https:: MANIFEST_UNKNOWN: manifest tagged by "azdev-deploy-1675379805" is not found; map[Tag:azdev-deploy-1675379805]: template.containers.main.image.
```

I looked in the portal and confirmed that there was no image with that tag in that registry.
I then ran `azd deploy` and it went fine.
I then ran `azd up` (to see if there was a problem with earlier stage) and it also went fine.

So perhaps it's just a transient issue, timing related? 

**To Reproduce**

Unclear that it's reproducible, given it only happened once for me.

**Expected behavior**

**Environment**
Information on your environment:
    * Language name and version: Python 3.11
    * IDE and version : Terminal, Mac OS M1 Ventura

**Comment by pamelafox** [comment] 2023-03-17 18:00
Also relevant: I found https://github.com/microsoft/azure-container-apps/issues/238 when researching the issue, so I ran the suggested command at the bottom, but it said enabled:

```
az acr config authentication-as-arm show -r  flasksurveysxvmcmelitbap4registry.azurecr.io
Command group 'acr config authentication-as-arm' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The login server endpoint suffix '.azurecr.io' is automatically omitted.
{
  "status": "enabled"
}
```

**Comment by jongio** [comment] 2023-03-22 23:07
Could you keep trying to reproduce it?  To me, it sounds not azd related, but I could be wrong

**Comment by wbreza** [comment] 2023-04-21 18:31
Not able to reproduce and attempted on different azure locations including `eastus2` and `westus2`.  Going to close this for now and we can reopen if it ends up being a widespread issue.

**Comment by savannahostrowski** [comment] 2023-05-01 15:16
I'm seeing this again this morning with todo-python-mongo-aca on eastus2

![image](https://user-images.githubusercontent.com/8949415/235475312-f172e10d-2f38-4c6c-9214-81dc354b0dd1.png)

**Comment by weikanglim** [comment] 2023-05-06 07:50
Based on the error, I suspect that the container image was recently published, and the time between publishing and creating a live container resource based on the image is short. Short enough that when ACA queries for the image, it doesn't yet exist. This is all happening in the service, so I'm not sure what we can realistically do here. We could definitely ask service teams to optimize for an eventual consistency issue, but I suspect the time window is small enough that this may prove to be hard. We could also introduce sleeps in bicep that increases the time window and lowers the chance of this happening.

The azd pattern of publishing an image and immediately using it on a live container is indeed a weird one, and I'm guessing this is why Azure users don't see this as often.

**Comment by pamelafox** [comment] 2023-05-06 13:24
How does `az containerapp up` handle that? (Granted, that's been less reliable for me recently than azd, but in theory it does a similar flow, creating an image and app)

**Comment by rajeshkamal5050** [comment] 2023-07-26 17:35
Closing it for now. Reopen it, if need be.

**Closed by rajeshkamal5050** 2023-07-26 17:35 UTC
Labels: cli
