### ISSUE TITLE
azd pipeline config  `Azure Dev Deploy` fail in pipeline

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#1870] opened 2023-04-04 12:54 UTC
**Describe the issue:**
Failing to deploy service web, when run `azd pipeline config --provider azdo`.

The error message as follows:
![image](https://user-images.githubusercontent.com/80496810/229797878-4b9a6d0f-2b14-4fd6-9ff6-a1c7e65a0492.png)

**Repro steps:**
1. Run command `azd login`.
2. Run command ` bash ./test-templates.sh -t xxx -b staging`
3. Run command `azd pipeline config --provider azdo`

**Environment:**
OS: Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code, WSL.
Template: .todo-csharp-cosmos-sql
todo-nodejs-mongo
todo-nodejs-mongo-swa-func
todo-python-mongo
todo-python-mongo-swa-func
todo-csharp-sql
todo-csharp-sql-swa-func
todo-java-mongo

Azd version: 0.7.0-beta.2-pr.2672227  (commit https://github.com/Azure/azure-dev/commit/dec4eb2c9f5932d3bd41f7e66b41c775c050ad48)

**Expected behavior:**
`azd pipeline config --provider azdo` can pass.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment] 2023-04-04 15:39
@vhvb1989 can you take a look at the azdo issue? Marked it as a blocker. Please update.

**Comment by wbreza** [comment] 2023-04-04 22:18
Duplicate of #1867 - only difference is that it is running in the azdo pipeline.

**Comment by rajeshkamal5050** [comment] 2023-04-04 22:39
Closing based on above finding.

**Closed by rajeshkamal5050** 2023-04-04 22:39 UTC
Labels: blocker, azdo, pipelines
