### ISSUE TITLE
SERVICE_XXX_RESOURCE_EXISTS environment variables are always `false` when passed as ARM Deployment params in CI environment

### ISSUE THREAD

**Issue by MarcelMichau** [Azure/azure-dev#4310] opened 2024-09-12 05:58 UTC
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.10.1 (commit 31409a33266fb4a5fdbb644bc83988e725d6c7c9)

**Describe the bug**
In a CI environment where the `SERVICE_XXX_RESOURCE_EXISTS` environment variables do not pre-exist in the `.azure/<environmentName>/.env` file, when running `azd provision`, the `SERVICE_XXX_RESOURCE_EXISTS` environment variables are always `false` when passed as Bicep params.

**To Reproduce**

1. Run `azd init --template Azure-Samples/todo-python-mongo-aca`
2. Run `azd provision` & wait for resources to finish provisioning
3. Open the `.azure/<environmentName>/.env` file & delete all environment variables except for `AZURE_ENV_NAME`, `AZURE_LOCATION` & `AZURE_SUBSCRIPTION_ID` to mimic the [environment variables passed to the CI task](https://github.com/Azure-Samples/todo-python-mongo-aca/blob/f8a0665acfd8bc4f16c08cf21b5cf93ee2d39367/.azdo/pipelines/azure-dev.yml#L41).
4. Run `azd provision --no-state` to force an infra deployment
5. When the provision operation starts, observe the values for `SERVICE_API_RESOURCE_EXISTS` & `SERVICE_WEB_RESOURCE_EXISTS` in the `.azure/<environmentName>/.env` file will update to `true`
6. Inspect the Deployment Inputs in the Azure Portal - the values for the `apiAppExists` & `webAppExists` parameters are still `false`:

![image](https://github.com/user-attachments/assets/2c2baea6-902c-475d-ba8c-9d25c415451e)

7. Subsequently running `azd provision --no-state` when the `SERVICE_XXX_RESOURCE_EXISTS` environment variables are present & set to `true` in the `.azure/<environmentName>/.env` file will correctly set the Bicep params to `true`:

![image](https://github.com/user-attachments/assets/dc795a7d-db5f-4976-b713-e9db5e3f24cd)

**Expected behavior**
Running `azd provision` in a CI environment should set `SERVICE_XXX_RESOURCE_EXISTS` environment variables to `true` prior to starting the Bicep deployment so that containers do not get swapped out with the `mcr.microsoft.com/azuredocs/containerapps-helloworld:latest` placeholder image during deployment.

**Environment**
Information on your environment:
Windows 11 Pro 23H2 - Build 22631.4169

**Additional context**
N/A

**Comment by weikanglim** [comment] 2024-09-13 19:13
This is indeed a bug. A more full description and a tentative plan of reworking how deploy works in this scenario is described fully in #4232. A related issue is described in #3116. FYI @wbreza 

>  should set SERVICE_XXX_RESOURCE_EXISTS environment variables to true prior to starting the Bicep deployment 

This may be an acceptable short-term fix. If we do such a thing, perhaps we could also avoid setting the output variable entirely and letting `azd` perform such determination. Thoughts?

**Comment by wbreza** [comment] 2024-09-20 18:01
Yes, I have confirmed a bug and believe the root cause here is from adding support of caching of bicep parameters during provider init phase and they don't get re-evaluated at deploy time and the azd environment was mutated between init & deploy. 

cc @vhvb1989

**Comment by weikanglim** [comment] 2024-09-20 18:32
@wbreza I see, thanks for the investigation. I think I have a change outside of the tree that was addressing #3973 that may address this as well. Let me see if that would work.

**Comment by weikanglim** [comment] 2024-10-02 16:50
This should be fixed with #3973 -- it's currently in the latest daily build if anyone wants to give it a try.

**Comment by MarcelMichau** [comment] 2024-10-03 15:09
Hi all

I've run through the reproduction steps detailed in the issue with azd version `1.11.0-beta.1-pr.4157496 (commit 300b7b3332d444b10a5cfd40e358bb31ef2c3384)` & can confirm that a subsequent deployment does set the `exists` variables to `true` as expected.

Thanks so much for getting this fixed!

**Comment by weikanglim** [comment] 2024-10-03 17:02
@MarcelMichau Thanks for giving it a try! I'm glad that it helped resolve your issue. The change will go out with the next release.

As a footnote, we are thinking about improving our strategy for container app deployments. If you have any thoughts around this, feel free to leave a note on ##4232.

**Closed by weikanglim** 2024-10-03 17:02 UTC
Labels: bug, question, customer-reported, issue-addressed
