### ISSUE TITLE
Support for "production" Postgres and Redis resources in Aspire.

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#3008] opened 2023-11-20 21:30 UTC
Today we use the Azure Container App Dev Services feature to run postgres and redis inside the ACA Container Apps Environment.  This is fine for dev time services, but is not what you'd want to do in production.

We need to provide a way to use "production" versions of this ([Azure Database for PostgreSQL](https://learn.microsoft.com/en-us/azure/postgresql/overview) and [Azure Cache for Redis](https://azure.microsoft.com/en-us/products/cache/)) as well as a way to switch between "dev" and "production".

I suspect that gesture "feels like" setting a property on the infrastructure configuration, and the generated infrastructure will have a parameter to control this behavior.

I suspect we can start at the global level and the think about this on a per resource basis later.

I suspect that this setting should be stored in the environment.  Perhaps it is managed by `azd infra config`?

**Comment by rajeshkamal5050** [comment] 2024-02-06 06:35
Duplicate of #3233

**Closed by rajeshkamal5050** 2024-02-06 06:35 UTC
Labels: enhancement, aspire
