### ISSUE TITLE
java

### ISSUE THREAD

**Issue by maksimdev16** [Azure/azure-dev#2491] opened 2023-07-09 11:02 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-dev.commands.cli.init
Error type: 1
Error Message: Process 'azd template list --output json' exited with code 1
Error: "azd" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.

Version: 0.6.0
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code - Insiders
Product Version: 1.81.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.js:2:928019
```

</details>

**Comment by rajeshkamal5050** [comment] 2023-07-10 16:35
Duplicate of #2454

**Closed by rajeshkamal5050** 2023-07-10 16:35 UTC
Labels: question, customer-reported
