### ISSUE TITLE
ContainerBaseImage from azurecr.io authentication

### ISSUE THREAD

**Issue by ABaxterScribe** [Azure/azure-dev#3571] opened 2024-03-21 17:14 UTC
**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 1.7.0 (commit 49d6adc2efb178083f61822e6b4715258560803d)

**Describe the bug**
A project in an aspire solution uses a container base image in an azure container registry. 
**azd up** fails as it is unable to access the registry. 

_C:\Program Files\dotnet\sdk\9.0.100-preview.2.24157.14\Containers\build\Microsoft.NET.Build.Containers.targets(210,5): error CONTAINER1016: Unable to access the repository 'aspnet9-ffmpeg' in the registry '***.azurecr.io'. Please confirm your credentials are correct and that you have access to this repository and registry._ 

I'm already logged in via **az acr login**.

**To Reproduce**
In an aspire solution add a ContainerBaseImage to one of the apps project files that points to a private registry.
azd init and azd up the solution.

**Expected behavior**
I think I expected azd to be able to get the container base image and build the container for this app as the shell should have been authenticated for the private registry.

**Environment**
Information on your environment:
   Windows 11, .net 9.0 preview, powershell 7.4.1, aspire preview 4

**Additional context**
I grabbed the dotnet publish command azd was running from the debug output (minus the redacted ContainerRegistry switch and that ran fine.

**Comment by rajeshkamal5050** [comment] 2024-04-09 16:48
Duplicate of #3435

**Closed by rajeshkamal5050** 2024-04-09 16:48 UTC
Labels: question, customer-reported, aspire
