### ISSUE TITLE
Enhance the "Use code in the current directory" workflow to generate default pipeline files

### ISSUE THREAD

**Issue by alexwolfmsft** [Azure/azure-dev#3359] opened 2024-02-14 17:16 UTC
When a user runs `azd init` and selects the `Use code in the current directory` option, it would be useful to have `azd` also create default pipeline files for GitHub Actions and Azure Pipelines. There could also be a flag to specify which one to create. This feature would also be especially useful for .NET Aspire apps.

Currently the user is forced to manually create the directory structure and copy and paste in default files from starter template repos. From a docs perspective, it also created overhead to have to describe this step for guidance that involves CICD.

**Comment by bradygaster** [comment] 2024-02-14 17:17
+1 to this. I was just working through using `azd pipeline config` for the first time and realized i didn't know a lot more than i didn't know about the process. i think it'd be great for AZD to output the workflow files if they're not already there. Even if we needed to add a new switch to do it and disable it by default, i think this would be a show-stopper feature.

**Comment by rajeshkamal5050** [comment] 2024-02-14 17:31
Duplicate of #2752

**Closed by rajeshkamal5050** 2024-02-14 17:31 UTC
