### ISSUE TITLE
Failed to create container with `todo-nodejs-mongo-swa-func` template

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#2517] opened 2023-07-12 10:02 UTC
**Describe the issue:**
When using `todo-nodejs-mongo-swa-func` template to build container for codespace, get error as follow:

![image](https://github.com/Azure/azure-dev/assets/80496810/8fd21a4b-f3a3-48a2-bf97-85693fd785cb)

**Repro Steps:**
1. Open repo: https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func
2. Open in a codesapce
![image](https://github.com/Azure/azure-dev/assets/80496810/d06fe009-5be1-433a-98f0-cea25e61a94c)
3. After container build is completed, a pop-up window appears as shown below, clicking the `View Creation Log` button to view the error log.
![image](https://github.com/Azure/azure-dev/assets/80496810/7b9f781f-52c2-41a9-bd1e-74c6dc29e94e)

**Expected behavior:**
 Creating codespace success with func template.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment] 2023-07-12 15:43
@vhvb1989 can you triage and see if this is a blocker for today's release?

**Comment by vhvb1989** [comment] 2023-07-12 16:43
I reproduced the issue from `main` branch on the template.
However, using `staging` branch works.

The problem is that `main` branch uses `FROM mcr.microsoft.com/vscode/devcontainers/base:0-bullseye}` for Dockerfile.
This img might've been updated recently and introduced this issue.

After releasing azd and updating `main` branch, this issue will be fixed.

See main v/s staging devcontainer changes here: https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func/compare/main...staging#diff-13bd9d7a30bf46656bc81f1ad5b908a627f9247be3f7d76df862b0578b534fc6R2

**Comment by vhvb1989** [comment] 2023-07-17 20:49
This should be fixed by now.  Please re-open if you still see the issue after latest release

**Closed by vhvb1989** 2023-07-17 20:49 UTC
Labels: codespaces, devcontainer
