### ISSUE TITLE
Unable to test user interactive login due to: `Your device is required to be managed to access this resource`

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/azure-dev#1029] opened 2022-10-28 10:27 UTC
**Describe the issue:**
Azure Dev deploys failed for `todo-python-mongo-terraform` and `todo-nodejs-mongo-terraform`

**Repro Steps:**
Run command: `bash ./test-templates.sh -t <template_name>  -b staging  -c false`.

**Error Message:**
![GetImage (32)](https://user-images.githubusercontent.com/20970631/198560379-6a89154b-7bfe-4f04-a23e-b925a2e57c31.png)

**Environment:**
OS: linux, codespaces, DevContainer in VS Code
Template:
https://github.com/Azure-Samples/todo-python-mongo-terraform 
https://github.com/Azure-Samples/todo-nodejs-mongo-terraform
Branch: staging
Azd version: 0.3.0-beta.6-daily.1947218 (commit e20ee4e6819f464f1f19d768d62bfaef493d46d8)

**Expected behavior:**
Azure Dev deploys successfully for todo-python-mongo-terraform and todo-nodejs-mongo-terraform.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment] 2022-10-28 15:38
@HadwaAbdelhalem can you try these terraform templates from codespaces?

**Comment by rajeshkamal5050** [comment] 2022-10-28 18:36
@HadwaAbdelhalem to try these terraform templates from Codespaces and will provide an update.

**Comment by HadwaAbdelhalem** [comment] 2022-10-28 22:33
@hattan and I looked into this issue turned out to be related to a managed device policy on the target subscription. In order to use AZ CLI authentication for terraform, [azurerm](https://github.com/hashicorp/go-azure-helpers/blob/bd6f0ab2a7633b9299c7dccb21eb37e104a5dad9/authentication/auth_method_azure_cli_token.go#L205) calls **az ad signed-in-user show** cmd  which was failing due to code space not being a managed device. 

The workaround is to use a service principal for Terraform Auth by setting the below arm env vars inside the code space before running azd  up or provision commands:
```
export ARM_SUBSCRIPTION_ID="<azure_subscription_id>"
export ARM_TENANT_ID="<azure_subscription_tenant_id>"
export ARM_CLIENT_ID="<service_principal_appid>"
export ARM_CLIENT_SECRET="<service_principal_password>"
```
 more details available [here](https://learn.microsoft.com/en-us/azure/developer/terraform/authenticate-to-azure?tabs=bash)

please test it and let me know.

**Comment by weikanglim** [comment] 2022-11-02 21:34
@danieljurek @rajeshkamal5050 We likely want to create a separate AAD tenant to be able to test user login scenarios in `codespace`, `devcontainer` environments. I think this will be more important as #1022 lands.

**Comment by pamelafox** [comment] 2022-11-08 20:57
I also run into this on todo-python-mongo (non-terraform) when trying to login with my @microsoft.com account inside Codespaces:

```
@pamelafox ➜ /workspaces/todo-python-mongo (main ✗) $ azd pipeline config
Using pipeline provider: GitHub
Creating or updating service principal az-dev-11-08-2022-18-24-51.

Error: failed to create or update service principal: failed retrieving application list, failed executing request: AzureCLICredential: ERROR: AADSTS530003: Your device is required to be managed to access this resource.
Trace ID: 884883b4-21c4-4259-ad97-d794c18d9f00
Correlation ID: b0449ee7-6df3-4797-8f97-26b9ea134453
Timestamp: 2022-11-08 18:24:51Z
To re-authenticate, please run:
az login --scope https://graph.microsoft.com/.default
```

It was fine with my non-microsoft.com account.

**Comment by vhvb1989** [comment] 2022-11-08 21:09
> I also run into this on todo-python-mongo (non-terraform) when trying to login with my @microsoft.com account inside Codespaces:
> 
> ```
> @pamelafox ➜ /workspaces/todo-python-mongo (main ✗) $ azd pipeline config
> Using pipeline provider: GitHub
> Creating or updating service principal az-dev-11-08-2022-18-24-51.
> 
> Error: failed to create or update service principal: failed retrieving application list, failed executing request: AzureCLICredential: ERROR: AADSTS530003: Your device is required to be managed to access this resource.
> Trace ID: 884883b4-21c4-4259-ad97-d794c18d9f00
> Correlation ID: b0449ee7-6df3-4797-8f97-26b9ea134453
> Timestamp: 2022-11-08 18:24:51Z
> To re-authenticate, please run:
> az login --scope https://graph.microsoft.com/.default
> ```
> 
> It was fine with my non-microsoft.com account.

@pamelafox , You can use this workaround: https://github.com/Azure/azure-dev/issues/1006#issuecomment-1293088916
For interactive login in codespaces

**Comment by v-xuto** [comment] 2022-12-07 03:44
@danieljurek This issue also occurs in the following cases:


- OS: Devcontainer in VS Code, Codespaces.
- Template: todo-nodejs-mongo-terraform.
- Branch: staging.
- Azd version: 0.4.0-beta.1 (commit https://github.com/Azure/azure-dev/commit/2bf7a529914d86d8e9f5d7b6f95a4f20a2351e01)
- Repro steps:
 1.Run azd init -t todo-nodejs-mongo-terraform -b staging.
 2.Run azd up

**Comment by myurasov** [comment] 2023-01-28 21:24
Is it fixed in latest CLI yet?

**Comment by v-xuto** [comment] 2023-01-29 07:59
@myurasov Terraform templates needs to install `az cli` additionally. After installation, log in with both `azd login` and `az login` commands, and this issue will not be reproduced. Besides, we will close this issue.

**Closed by v-xuto** 2023-01-29 07:59 UTC
Labels: terraform
