### ISSUE TITLE
[Issue] Consider having azd init extract into a new directory

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#1927] opened 2023-04-11 17:02 UTC
Currently, `azd init -t` extracts files into the current directory. That gives me the heebie jeebies, since I'm nervous about accidentally not cd'ing into a new directory, so I never use `-t` nor do I recommend that others use it. (I did accidentally extract into my root directory once and spent a while cleaning up the extracted files, so this overly reactive emotion is somewhat justified).

I would much prefer that -t made a new directory inspired by the template name (with random suffixes as needed), similar to the `git clone` behavior.

That would also simplify README instructions which currently have to tell people to make a new directory first.

**Comment by savannahostrowski** [comment] 2023-04-12 01:16
Yep - 100% agree. This is a dupe of #1638 and is planned for the next iteration.

**Comment by rajeshkamal5050** [comment] 2023-04-13 15:53
Failing for a non-empty folder should be handled as part of #1638 for GA 
Creating a new directory should be handled as part of #181 post GA

Closing this as a duplicate.

**Closed as completed by rajeshkamal5050** 2023-04-13 15:53 UTC
Labels: bug, area/core-cli
