### ISSUE TITLE
`azd pipeline config` login issues

### ISSUE THREAD

**Issue by chuwik** [Azure/azure-dev#2640] opened 2023-08-17 22:10 UTC
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.2.0 (commit 99ea7577f0df0df2ba34b677da189fafba18c0f7)

**Describe the bug**
`azd pipeline config` is failing to create a service principal, asking me to reauthenticate with `azd auth login --scope https://graph.microsoft.com/.default.`. This command never succeeds, after I login successfully from a domain managed PC it still shows an error saying that my device must be managed by Microsoft to access the resource.

![image](https://github.com/Azure/azure-dev/assets/403428/74b6f131-8699-4d36-9321-ed1c00f7e24c)

**To Reproduce**
`azd auth login --use-device-code`
`azd pipeline config`
`azd auth login --scope https://graph.microsoft.com/.default.`

**Expected behavior**
Login succeeds and azd can finish configuring the pipeline.

**Environment**
Information on your environment:
    * Windows 11, Powershell 7.3.6

**Comment by rajeshkamal5050** [comment] 2023-08-18 16:00
Seems similar to issue [azd auth login with scope does not work #2277](https://github.com/Azure/azure-dev/issues/2277) @weikanglim @vhvb1989 do we have any workaround for this?

**Comment by weikanglim** [comment] 2023-08-18 17:02
Hi @chuwik 

From the error message, specifically "Your sign-in was successful but your admin requires the device requesting access to be managed by Microsoft to access this resource"

It looks like your sign-in was successful, but the device isn't trusted based on the configured policies on the Microsoft tenant.

I would try that following:

1. Make sure you're logged into Edge using your work profile and try logging in via Edge. This is usually the reason why the device isn't trusted.
3. Try reproducing this going to the [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) API and clicking the Person icon on the top right of the screen to sign in to your @Microsoft.com account to see if you get any additional errors.
<img width="291" alt="image" src="https://github.com/Azure/azure-dev/assets/2322434/dce540fa-a144-4771-993d-44c619f6764f">

**Comment by chuwik** [comment] 2023-08-18 19:23
Both options check out:
- I'm using Edge with work profile, it's even showing a 'Managed by your organization' message in the Settings menu
- I can login without problems from the Graph Explorer

I'm running into login issues for azd provision too. Here's the chain of commands and errors I'm seeing:

azd auth login -> successful

azd provision -> ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: starting deployment to subscription: login expired, run `azd auth login --scope https://management.core.windows.net//.default to log in

azd auth login --scope https://management.core.windows.net//.default -> successful

azd provision -> ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: creating parameters file: fetching current principal id: getting tenant id for subscription <sub-id>. Error: failed to resolve user access to subscription with ID <sub-id>. If you recently gained access to this subscription, run `azd auth login` again to reload subscriptions. Otherwise, visit this subscription in Azure Portal using the browser, then run `azd auth login`. 

I get stuck in this loop, but azd provision never succeeds.

Note: I'm an owner of the subscription, see it in the portal, etc. I've obscured the sub-id in the messages above.

**Comment by weikanglim** [comment] 2023-08-18 20:00
If you run `azd env get-values`, does an entry for `AZURE_SUBSCRIPTION_ID` show up?

**Comment by chuwik** [comment] 2023-08-18 20:20
It does.

I deleted ~/.azd and `azd provision` is now working. Will try with `azd pipeline config` after, maybe clearing that dir did the trick.

**Comment by chuwik** [comment] 2023-08-18 20:27
Clearing `.azd` and retrying fixed all the auth issues I had, now I can run both `azd provision` and `azd pipeline config`. Feel free to close, I can provide more info if it can help you investigate. Unfortunately I didn't keep a copy of .azd before deleting it.

**Comment by weikanglim** [comment] 2023-08-24 23:30
We were able to find a copy of an azd user's `~/.azd` and track down the cause. Closing this in favor of #2659.

**Closed by weikanglim** 2023-08-24 23:30 UTC
Labels: bug, azdo, pipelines, authn

**Comment by tlunsfordCXP** [comment] 2025-04-26 23:00
For others having this issue with `azd` and .NET Aspire, check the `/.azure/.env` file in your solution root. For me, the value for `AZURE_SUBSCRIPTION_ID` was being populated with the subscription name and not the ID. Updating it to have the subscription id GUID value resolved the issue for me.

To be sure, the error I'm seeing is in running `azd up` or `azd provision`. Error text is: `ERROR: initializing provisioning manager: resolving bicep parameters file: fetching current principal id: getting tenant id for subscription YOUR SUBSCRIPTION NAME HERE. Error: failed to resolve user 'YOUR EMAIL ADDRESS HERE' access to subscription with ID 'YOUR SUBSCRIPTION NAME HERE'. If you recently gained access to this subscription, run `azd auth login` again to reload subscriptions.
Otherwise, visit this subscription in Azure Portal using the browser, then run `azd auth login``
