### ISSUE TITLE
No error message if run from root of user directory (.azure file conflict) 

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#1400] opened 2023-01-16 22:16 UTC
Identified in recent user study.

This issue is documented in our Troubleshooting page, however it would be faster and more direct to help them course-correct with an error message in the CLI. Additionally, this customer did find our Troubleshooting page, but did not find the relevant information under "The .azure directory" heading. I believe this is because the heading does not convey the issue they were experiencing, so they did not think it was relevant. Contrast this with another heading in the page,  "azd up or az provision fails, "which does describe an issue and may make a customer stop and read if it is relevant to them. 

The ideal fix is to have an error message in this case, a suggested backup fix is to change the heading on the troubleshooting page to something like "azd becomes non-responsive."that you get a success message, but you didn't actually successfully install all pre-req as well to use azd (e.g. can get successful azd install without having az, which will lead to failures when they try to use azd). This success message causes customers not to go back in the pre-req steps because they assume that if azd is successfully installed, then all pre-reqs to use azd must also be installed. 

![image](https://user-images.githubusercontent.com/8701892/212773368-93105db5-c995-47d6-8516-0a851a7ae413.png)

**Comment by ellismg** [comment] 2023-01-17 21:55
The crux of the issue is that the `az` CLI writes a `.azure` folder in the user's home directory to store configuration information and this conflicts with our use of `.azure` for the directory to store project specific information.  We could consider using something like `.azd` but that would conflict with the `.azd` directory /we/ create in the user's home directory to store our configuration information.

I am wondering if we should move away from using `.azure` in this way, and instead pick a unique name that is not used by either tool for configuration information.

**Comment by vhvb1989** [comment] 2023-01-17 23:39
@ellismg , I would suggest renaming `.azure` to `.azure-dev`

**Comment by rajeshkamal5050** [comment] 2023-01-18 21:32
@vhvb1989 @ellismg prefer .azd over .azure-dev. Since `azd` being our root command as well.

**Comment by vhvb1989** [comment] 2023-01-18 23:08
@rajeshkamal5050 `.azd` conflicts with `~/.azd` folder at the user's home directory.  In case we run `azd` within the home directory.
We need unique name for:
- setting folder at home directory (currently .azd)
- env folder at working directory (currently .azure)
- respect and avoid collision with `.azure` from az cli at home directory (currently.az

**Comment by rajeshkamal5050** [comment] 2023-01-19 07:59
@ellismg @vhvb1989 thanks for the clarifications.
- settings folder `.azd` makes sense as it is agnostic to environments.
- instead of `.azure` and being environment specific. can't we use `.azdenv` which will be unique in the context of the working directory?

**Comment by rajeshkamal5050** [comment] 2023-01-23 21:29
@ellismg can we also take care of this as part of the environment proposal and implementation?

**Comment by rajeshkamal5050** [comment] 2023-04-13 06:34
Marking this as a duplicate of #1638

**Closed by rajeshkamal5050** 2023-04-13 06:34 UTC
Labels: bug, cli, user-study
