### ISSUE TITLE
Cannot run `azd init` or `azd up` - "no oid claim"

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1842] opened 2023-03-31 21:36 UTC
![image](https://user-images.githubusercontent.com/8949415/229237105-d29358f0-ed74-4fdf-81f7-b9b442f5beb2.png)

I know we have #1758 but this error came up after a fresh login into my personal subscription. Happy to close this as a dupe if it's the same root cause but do all of our commands require MSGraph access? This seems like a major bug, if so.

This is a fresh `up` as well.

**Comment by vhvb1989** [comment] 2023-04-01 23:33
> do all of our commands require MSGraph access

We need msgraph access for `init/up` and for `pipeline config`
For `init/up` we use it to get the PRINCIPAL_ID from the current logged in user.
For `pipeline config` we need it to create a SERVICE_PRINCIPAL to auth the pipeline.

@weikanglim , this is what I mentioned earlier, for a customer who has never used their browser before to auth with `az cli`, they will get this error, b/c azd is not asking for msgraph scope.

Agree with you @savannahostrowski , this is a major bug.  azd must make sure that the current logged in user has msgraph access.

**Comment by weikanglim** [comment] 2023-04-03 17:51
I'm guessing this may only happen for a personal user? `azd init` and `azd up` works fine for all our current test users.

The error message means that:
1. We failed `msgraph` access
2. We failed to extract the user id from the JWT token

https://github.com/Azure/azure-dev/blob/23cf941b3e934e2f51606d467041e892d49e65bd/cli/azd/pkg/azureutil/principal.go#L22-L39

**Comment by vhvb1989** [comment] 2023-04-06 01:27
still can't reproduce.
Removing `blocker` for now as this issue might be affecting only folks using a personal account and the Visual Studio Enterprise Subscription.

**Comment by rajeshkamal5050** [comment] 2023-04-13 04:23
@weikanglim @vhvb1989 There are many issues floating around on the login scope/oid. Closing this as a duplicate of #1758

**Closed by rajeshkamal5050** 2023-04-13 04:23 UTC
Labels: cli
