### ISSUE TITLE
Unexpected redacted:key in JSON at position 0

### ISSUE THREAD

**Issue by timheuer** [Azure/azure-dev#1828] opened 2023-03-30 16:56 UTC
Clicked refresh icon on the Workspace area of the Azure extension:
![image](https://user-images.githubusercontent.com/4821/228909809-c151b564-a7ba-4a73-8d86-63e1479029cf.png)

Got the error notification here.

Action: azure-dev.views.workspace.application.resolve
Error type: SyntaxError
Error Message: Unexpected redacted:key in JSON at position 0

Version: 0.4.2
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

<details>
<summary>Call Stack</summary>

```
WorkspaceAzureDevShowProvider.getShowResults extension.js:2:899603
extension.js:2:925496extension.js:2:925496
```

</details>

**Comment by rajeshkamal5050** [comment] 2023-03-31 17:36
@bwateratmsft can you take a look at it? Please let us know if it is azd core issue?

**Comment by bwateratmsft** [comment] 2023-03-31 17:55
@timheuer can you run this command and share the output? `azd show --output json`

**Comment by bwateratmsft** [comment] 2023-03-31 18:04
Well, that's normal. I found that if you try the command in a directory without an `azure.yaml` file, you get this message:
> Error: no project exists; to create a new project, run `azd init`

The first character being `E` matches the error toast. However, we're not _supposed_ to run this command at all if there's no `azure.yaml` file. I wonder if it's empty or if it's a complete different file type?

**Comment by timheuer** [comment] 2023-03-31 18:06
Repo: https://github.com/timheuer/ScaleDotNetOnContainerApps

**Comment by timheuer** [comment] 2023-03-31 18:42
And of course now it works.
![image](https://user-images.githubusercontent.com/4821/229203639-4673d643-d7d5-4e53-8931-414fa33dfe23.png)

**Comment by bwateratmsft** [comment] 2023-03-31 18:46
The bug knows I'll squash it if I catch it 😄

**Comment by bwateratmsft** [comment] 2023-06-12 14:05
I'll resolve this as a duplicate of #2072

**Closed by bwateratmsft** 2023-06-12 14:05 UTC
Labels: cli, vscode
