### ISSUE TITLE
Remove dependency on local docker install.  Allow deploy to "containerapp" using ACR build task to build the container.  

### ISSUE THREAD

**Issue by khowling** [Azure/azure-dev#3582] opened 2024-03-23 10:14 UTC
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here: azd version 1.7.0 (commit 49d6adc2efb178083f61822e6b4715258560803d)

**Describe the bug**

Many organisations don't have docker installed locally on developers laptops, please remove the dependency on docker for deploying to containerapps / aks

ERROR: required external tools are missing:
 - Docker is not installed, see https://aka.ms/azure-dev/docker-install to install

**To Reproduce**
Run azd deploy or provision on a project with a host of containerapp on a machine without docker installed

**Expected behavior**
I would like to configure ACR to execute the container build taks when deploying to containerapps, to remove the dependency on having docker installed locally, removing it from the developers innerloop.  When running the app locally, I would just have azd launch the process directly (eg npm run)

**Comment by rajeshkamal5050** [comment] 2024-03-26 22:49
Seems duplicate of #509

**Closed** 2024-03-26 22:51 UTC
