### ISSUE TITLE
[AspireDeployment] `azd vs-server` should support authentication with clients

### ISSUE THREAD

**Issue by anvillan** [Azure/azure-dev#3320] opened 2024-02-08 01:42 UTC
The `azd vs-server` should support authentication (Azure Entra) with clients.

As for today, it is assumed clients starting, sending requests to the `azd vs-server` have already authenticated (`azd auth login`) to the `azd` process. However, apart for the implied security reasons, that is not always true, resulting in an unexpected experience for users that are not aware of such requirement.

There are various aspects to consider:

a. Should the authentication token be passed on server startup or with every request?

b. If a user _changes_ account/subscription, how is the new auth token be passed to the server? Should it be restarted?

c. How should authentication errors be reported back for a request?

Signatures or return type/data would be changed, so VS IDE should be informed to adjust current API contracts.

**Comment by ellismg** [comment] 2024-02-13 18:12
We should solve this the same way we solve the problem with VS Code - where we provide a way for VS to expose a server that `azd` uses for authentication information.  This will be the cleanest from the `azd` side and also give the most flexibility to the caller.  I will write up how this works end to end in VS Code, but you can also take a peak at https://github.com/Azure/azure-dev/pull/2541 in the interim to see the PR that added the feature and how it works.

**Comment by anvillan** [comment] 2024-02-13 20:59
@ellismg Let's talk about this bug in our next Aspire meeting. 

After discussing it with @abpiskunov, we think it'd be easier if we pass a token to the `vs-server` rather than spawning another process (though it's doable) but adds more complexity to the scenario than what it might be solved by just passing in a new parameter.

**Comment by ellismg** [comment] 2024-02-15 19:06
> After discussing it with @abpiskunov, we think it'd be easier if we pass a token to the vs-server rather than spawning another process (though it's doable) but adds more complexity to the scenario than what it might be solved by just passing in a new parameter.

The problem is you cannot just pass in a token - the token is bound to the specific service today - and over time POP tokens will mean that there is a unique token per request.  We need a way for `azd` to request a token from VS when it needs it, presenting to VS all the information that it has as part of the token request.  Passing a fixed value will not work long term.

**Comment by anvillan** [comment] 2024-02-15 19:15
@ellismg 

Understood. Let's better discuss the whole scenario in our next meeting. 

I think we're missing some of the aspects you point out.

**Comment by ellismg** [comment] 2024-02-22 20:57
@anvillan - I wrote up how the external authentication stuff works today and checked in in here: https://github.com/Azure/azure-dev/blob/main/cli/azd/docs/external-authentication.md.  You can follow this protocol without any changes to `azd` itself, all of the code is checked in and works today.

On the call, we discussed how you might want a different strategy vs an HTTP 1.1 Web Server, and instead would like to pass the connection information to `InitializeAsync` and that you would rather we speak JSON-RPC 2.0 over websockets instead of doing a `POST` over HTTP 1.1.

I'm happy to do that, but I need to understand the changes on your end.  I think it looks like the following:

1. Add a new argument to `InitializeAsync` which contains the connection information.  Would it be possible for you all to pass a fully qualified URI like `ws://127.0.0.1:12345/some/optional/path` and we just connect to that and start speaking our agreed on protocol, or will it just be the path?
2. If we are using JSON-RPC here - What's the name of the RPC method you are exposing, and the arguments?  It would be ideal if it looked something like:

`Task<AccessToken> GetTokenAsync(string[] scopes, GetTokenOptions options, CancellationToken cancellationToken)`

Internally, the implementation of your method would end up calling [GetToken](https://learn.microsoft.com/en-us/dotnet/api/azure.core.tokencredential.gettoken?view=azure-dotnet#azure-core-tokencredential-gettoken(azure-core-tokenrequestcontext-system-threading-cancellationtoken)) on whatever Azure SDK credential you have and handle marshalling the result back via the RPC.

Let me know what makes it easiest from the VS side to integrate, and we can make whatever changes on our end to start speaking the new protocol.

**Comment by ellismg** [comment] 2024-02-22 22:41
Thanks, @anvillan!

> Thanks for the details. Let's discuss it in our meeting.

I had to miss today's meeting due to some personal issues - I'll set up some time with you and @abpiskunov to discuss.

**Comment by rajeshkamal5050** [comment] 2024-02-23 06:42
Tirage update: 
- Scope is big on VS side to integrate with the external authentication flow in Azd.
- @anvillan to post the assumptions and follow-up questions to @ellismg @weikanglim 
- Not a must-fix item for `VS 17.10 Preview 2`. Moving to next milestone.

@anvillan @weikanglim @abpiskunov @ellismg

**Closed** 2024-03-16 05:42 UTC
Labels: vs, aspire
