### ISSUE TITLE
Using federated trust in GH Action, I had to add azd login between azd executions

### ISSUE THREAD

**Issue by jpocloud** [Azure/azure-dev#1740] opened 2023-03-16 16:32 UTC
**Output from `azd version`**
azd version 0.7.0-beta.1 (commit 9ce71659f7688d0dc3dda8b84e5accedca58cf01)

**Describe the bug**
I have to add duplicate steps for azd login inside a single job within GH Action using the new Federated trust with Github. It appears either the token generated from azd login was expiring too soon or execution of azd deploy commands were wiping it out. The reason wasn’t shown in logs, just that I was not logged in and needed to run azd login, here was the message:
Error: not logged in, run `azd login` to login
Error: Process completed with exit code 1.

Note that prior to using the federated GH integration (using SPN Secret), this was not an issue with azd.

**To Reproduce**
Setup azd for GH actions by running azd pipeline config, then execute these as different steps in github action, on execution of #3, I got a request to azd login. In my scenario, step #2 took roughly 20 minutes to complete.
1- `azd login  --client-id ${{ secrets.AZURE_CLIENT_ID }}  --federated-credential-provider "github"  --tenant-id ${{ secrets.AZURE_TENANT_ID }}`
2 - `azd provision --no-prompt`
3 - `azd env set AZURE_RESOURCE_GROUP ${{ secrets.AZURE_ENV_NAME }}daily2-rg`

**Expected behavior**
Did not expect to need to azd login again.

**Environment**
Information on your environment:
Ubuntu-latest in GH Action runner, using image: mcr.microsoft.com/azure-dev-cli-apps:latest

**Comment by rajeshkamal5050** [comment] 2023-03-16 17:21
@ellismg take a look at it.

**Comment by rajeshkamal5050** [comment] 2023-04-12 21:36
@wbreza can you take a look at this OIDC timeout issue?

**Comment by rajeshkamal5050** [comment] 2023-04-13 00:43
Seems to be a duplicate of #1901 https://github.com/Azure/azure-dev/issues/1901#issuecomment-1506136846

Closing this one.

**Closed by rajeshkamal5050** 2023-04-13 00:43 UTC
Labels: bug
