### ISSUE TITLE
Easy way to check what account I am logged into

### ISSUE THREAD

**Issue by irinasmoke** [Azure/azure-dev#986] opened 2022-10-24 23:16 UTC
I would like to able to check easily what Azure account I am logged into without having to do a deployment to see the list of subscriptions.

`azd login --check-status` only says if you are logged in or not.

I can't find info that says whether I can assume that az and azd login statuses are one and the same, so I don't know if I can trust the output from `az account list` to be is what azd is using.

**Comment by vhvb1989** [comment] 2022-10-24 23:24
Thank you for using azd!! :)

`azd` currently uses `AzureCLICredential`.  So, it depends on whatever the `az cli` is logged in to. 

The final experience around `log in` for `azd` is still WIP

**Comment by rajeshkamal5050** [comment] 2022-10-25 16:25
@irinasmoke new azd config command for the default account/subscription #955

**Comment by irinasmoke** [comment] 2022-10-25 19:33
> @irinasmoke new azd config command for the default account/subscription #955

After reviewing this feature, my understanding is that it takes care of the case where you may have one account with many subscriptions and don't want to scroll/pick each time. 

However, I am also looking to cover the case where I have multiple Azure accounts (e.g. personal and enterprise) and need to know which I am logged into.

**Comment by irinasmoke** [comment] 2022-10-25 19:39
> Thank you for using azd!! :)
> 
> `azd` currently uses `AzureCLICredential`. So, it depends on whatever the `az cli` is logged in to.
> 
> The final experience around `log in` for `azd` is still WIP

Do we make this explicit anywhere? My suggestion is to, for now, make it clear in docs/`azd login --help` that az cli login = azd login, and in the future azd login experience to make sure this scenario (I need to check what account I am logged into) is covered.

**Comment by savannahostrowski** [comment] 2023-05-10 19:11
This has evolved a bit since this was filed but IMO, we should at the very least show what account(s) are authenticated

![image](https://github.com/Azure/azure-dev/assets/8949415/70370313-54a6-405f-8c2f-4151bbbf65bf)

**Comment by jongio** [comment] 2023-10-20 22:20
This is related:
https://github.com/Azure/azure-dev/issues/1745

I'm working on writing a script that needs to check if a user is logged into azd.  If we go with the current design of showing "Logged into Azure", then my script would have to parse that text.  It would be create if we could have a flag that was something like --is-logged-in that returns a bool.  Or something more structured so automation with azd is that much easier.  Thoughts @weikanglim ?

**Comment by jongio** [comment] 2023-10-20 23:24
Looks like `azd auth token --output json` gives me what I need.

**Comment by weikanglim** [comment] 2023-10-24 16:33
@jongio 

This functionality exists as:
```
~ azd auth login --check-status --output json                  
{
  "status": "success",
  "expiresOn": "2023-10-24T17:35:40.934596732Z"
}
```

**Comment by rajeshkamal5050** [comment] 2024-03-12 21:04
Closing based on https://github.com/Azure/azure-dev/issues/986#issuecomment-1777608905

**Closed by rajeshkamal5050** 2024-03-12 21:04 UTC
Labels: command, feature, hacktoberfest, area/core-cli

**Comment by john0isaac** [comment] 2024-03-12 21:11
@rajeshkamal5050 the issue is asking about showing the logged-in account not whether you are logged in or not.
Also, the related issue #2976 was asking for the same thing which is a way to show the logged-in email or principal id.

The comment mentioned a way to show whether you are logged in or not which doesn't solve the issue here or in #2976

**Comment by rajeshkamal5050** [comment] 2024-03-12 21:31
Yes, you are right @john0isaac. Adding some notes.

Initial ask for `showing the current logged-in user details` is similar to #1745. Marking this as duplicate of #1745.

In the middle it got hijacked for `need to check if a user is logged into azd` which can be achieved by `azd auth login --check-status --output json`

**Comment by jvmap** [comment] 2025-03-11 14:23
Is this really a duplicate of #1745 ? I still can't figure out how to tell which subscription `azd` is using.
