### ISSUE TITLE
Publish templates to azure samples browser

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#526] opened 2022-08-25 20:10 UTC
Let's get the templates published here: 

https://docs.microsoft.com/en-us/samples/browse/

We need to add necessary yaml header to READMEs and the azure-samples publisher account to azure-dev

**Comment by rajeshkamal5050** [comment] 2022-10-05 20:28
Since its a P2 and also, we have the templates gallery site https://aka.ms/awesome-azd/

Moving it to backlog for now.

**Comment by savannahostrowski** [comment] 2022-10-11 20:27
This is a dupe of https://github.com/Azure/azure-dev/issues/425. @jongio which do you want to leave open?

**Comment by jongio** [comment] 2022-10-20 17:40
two diff imo.
This one is "get them out there".   #425 is work with docs team to make azd samples standout in the browser with a blue check.

**Comment by rajeshkamal5050** [comment] 2023-01-13 00:01
`How can we onboard our samples to Learn?`

Understanding you have a repo in Azure-Samples org, we need to ensure that the ingestion process is aware of your repo. To do this, we need to complete this onboarding form: https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR17IcoC-CnxGgErwh2l4_cBUNENaVE5FUk1CQ0kwTlo0QkVZUVhCUThXRC4u

`What is the process for external contribution on Learn Code Samples today?`

As it stands, our external contribution is though GitHub. We do not offer another modality for community publishing on samples at this time. https://review.learn.microsoft.com/en-us/help/contribute/samples/concepts/basics?branch=main#how-can-customers-outside-microsoft-contribute

**Comment by savannahostrowski** [comment] 2023-01-20 21:03
@rajeshkamal5050 This should probably go into 0.7 or 0.8 milestone.

**Comment by weikanglim** [comment] 2023-02-13 17:18
Onboarding docs are available here: https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main#supported-metadata-fields-for-readmemd

**Comment by savannahostrowski** [comment] 2023-02-14 15:50
Do we have to make the title "ToDo" at all? I've been thinking that we might want to reframe the templates to be more about the scenario that they enable. For instance, with the ToDo templates, we are really looking at a web app written in C# using Azure SQL Database. Most users won't necessarily care about the ToDo part and will rip that source code out in favour of their own code. That said, I worry that by promoting the ToDo part too heavily, some users might not think that the template is relevant to them.

That said, could we do something like "Web application with a C# API and Azure SQL Database"? Or is that too generic?

cc: @austinauth for any additional thoughts here (because we talked about this extensively for awesome-azd)

**Comment by Austinauth** [comment] 2023-02-14 16:34
A few thoughts:

**Re: Calling out service names in the title/description**
The official Microsoft sample site is fairly restrictive around how a user can discover new templates. You cannot filter by things like service or framework, and only two metadata tags are surfaced on the card itself. So while, "Web application with a C# API and Azure SQL Database" is slightly generic, I think its important to highlight the services in the title or the short description like you have.

**Re: Including ToDo in the name**
I'm still split on this. ToDo isn't really a _use case_, but I do think it helps affirm that this is a simple application you can conceptualize. As opposed to something more esoteric like some of the examples I've seen: _Django SQL Driver_ or _Collision_. **That being said, we should be good removing it from the title as long as its in the description.**

**Re: My initial thoughts on naming & use cases**

These are technically tutorials, but I like how [Docker](https://docs.digitalocean.com/tutorials/) consistently starts their tutorial name with a verb. IMO it makes everything seem more approachable.

![image](https://user-images.githubusercontent.com/6994218/218798322-82d0cc94-3e71-4afb-8b5e-16ec10093772.png)

Another interesting example is [AWS's Solution Library](https://aws.amazon.com/solutions/?awsm.page-solutions-whats-new=1). While its not easy to find a sample by a particular service, they do a pretty good job of enabling discovery by a particular use case or vertical.

**Comment by weikanglim** [comment] 2023-02-16 22:01
@savannahostrowski @Austinauth 

Thanks for the good callout. One thing to consider here is that by default, the sample metadata will use the first Markdown heading (H1) as the title, which we have "ToDo application" in the title. Our options are here to either override it, or maybe we should make the "scenario" apparent in the description?

To simplify things, here's all are templates below. We need to come up with specific wording for the Title (displayed in the top of the card), and 150-word Description (display in the body of the card):

| Template | Title | Description |
| - | - | - |
| todo-csharp-cosmos-sql | ToDo Application with a C# API and Azure Cosmos DB SQL API | |
| todo-csharp-sql | ToDo Application with a C# API and Azure SQL Database | |
| todo-csharp-sql-swa-func | ToDo Application with a C# API and Azure SQL DB on Static Web Apps and Functions | |
| todo-java-mongo | ToDo Application with a Java API and Azure Cosmos DB API for MongoDB on Azure App Service | |
| todo-java-mongo-aca | ToDo Application with a Java API and Azure Cosmos DB API for MongoDB on Azure Container Apps | |
| todo-nodejs-mongo | ToDo Application with a Node.js API and Azure Cosmos DB API for MongoDB on Azure App Service | |
| todo-nodejs-mongo | ToDo Application with a Node.js API and Azure Cosmos DB API for MongoDB on Azure App Service (Terraform) | |
| todo-nodejs-mongo-aca | ToDo Application with a Node.js API and Azure Cosmos DB API for MongoDB on Azure Container Apps | |
| todo-nodejs-mongo-swa-func | ToDo Application with a Node.js API and Azure Cosmos DB API for MongoDB on Static Web Apps and Functions | |
| todo-python-mongo | ToDo Application with a Python API and Azure Cosmos DB API for MongoDB on Azure App Service | |
| todo-python-mongo | ToDo Application with a Python API and Azure Cosmos DB API for MongoDB on Azure App Service (Terraform) | |
| todo-python-mongo-aca | ToDo Application with a Python API and Azure Cosmos DB API for MongoDB on Azure Container Apps | |
| todo-python-mongo-swa-func | ToDo Application with a Python API and Azure Cosmos DB API for MongoDB on Static Web Apps and Functions | |

Card for reference:
![image](https://user-images.githubusercontent.com/2322434/219496731-89c56b3c-cc31-4bc6-bc20-88cf3ee215b0.png)

**Comment by savannahostrowski** [comment] 2023-02-21 16:39
@gkulin has offered to help get these titles and descriptions tee'd up!

**Comment by gkulin** [comment] 2023-02-22 19:39
> We need to provide a less than 150-word description that shows up on each sample's card in the gallery.

@weikanglim Do you mean 150 characters? Based on the descriptions you suggested, I think that's what you meant. But as I am looking through the gallery, I am coming across quite a few descriptions that are more than 150 characters (but not by much, I think the longest I saw was 167). Where did you get that 150 limit from?

**Comment by gkulin** [comment] 2023-02-22 23:22
re: Wei's chart with the info we need to fill. 

I went with Savannah's suggestion of not having "ToDo" in the title since that isn't really (most of the time) relevant to the user 

One thing to note is that the descriptions are essentially the title but in more words. 

Wei had the idea of [a standard description that ties into azd](https://github.com/Azure/azure-dev/issues/526#issuecomment-1428385854) which I think might work well. So, the standard description I would suggest:
> A complete ToDo list web app using Azure Developer CLI (azd) to build, deploy, and monitor
        
**Template**|**Title**|**Description**
:-----:|:-----:|:-----:
todo-csharp-cosmos-sql|Web Application with a C# API and Azure Cosmos DB SQL API|A complete ToDo app with C# API and Azure Cosmos DB SQL API for storage. Uses Azure Developer CLI (azd) to build, deploy, and monitor
todo-csharp-sql|Web Application with a C# API and Azure SQL Database|A complete ToDo app with C# API and Azure SQL database for storage. Uses Azure Developer CLI (azd) to build, deploy, and monitor
todo-csharp-sql-swa-func|Web Application with a C# API and Azure SQL DB on Static Web Apps and Functions|A complete ToDo app with C# isolated Azure Functions for the API and Azure SQL database for storage. Uses Azure Developer CLI (azd) to build, deploy, and monitor
todo-java-mongo|Web Application with a Java API and Azure Cosmos DB API for MongoDB on Azure App Service|A complete ToDo app with Java API and Azure Cosmos for MongoDB for storage. Uses Azure Developer CLI (azd) to build, deploy, and monitor
todo-java-mongo-aca|Web Application with a Java API and Azure Cosmos DB API for MongoDB on Azure Container Apps|A complete ToDo app on Azure Container Apps with Java API and Azure Cosmos API for MongoDB for storage. Uses Azure Developer CLI (azd) to build, deploy, and monitor
todo-nodejs-mongo|Web Application with a Node.js API and Azure Cosmos DB API for MongoDB on Azure App Service|A complete ToDo app on Azure App Service with Java API and Azure Cosmos API for MongoDB for storage. Uses Azure Developer CLI (azd) to build, deploy, and monitor
todo-nodejs-mongo-terraform|Web Application with a Node.js API and Azure Cosmos DB API for MongoDB on Azure App Service (Terraform)|A complete ToDo app on Azure App Service with Java API and Azure Cosmos API for MongoDB for storage. Uses Azure Developer CLI (azd) to build, deploy, and monitor
todo-nodejs-mongo-aca|Web Application with a Node.js API and Azure Cosmos DB API for MongoDB on Azure Container Apps|Complete ToDo app on Azure Container Apps with Node.js API and Azure Cosmos API for MongoDB for storage. Uses Azure Developer CLI (azd) to build, deploy, and monitor
todo-nodejs-mongo-swa-func|Web Application with a Node.js API and Azure Cosmos DB API for MongoDB on Static Web Apps and Functions|A complete ToDo app with Node.js API and Azure Cosmos API for MongoDB for storage. Uses Azure Developer CLI (azd) to build, deploy, and monitor
todo-python-mongo|Web Application with a Python API and Azure Cosmos DB API for MongoDB on Azure App Service|A complete ToDo app with Python FastAPI and Azure Cosmos API for MongoDB for storage. Uses Azure Developer CLI (azd) to build, deploy, and monitor
todo-python-mongo-terraform|Web Application with a Python API and Azure Cosmos DB API for MongoDB on Azure App Service (Terraform)|A complete ToDo app with Python FastAPI and Azure Cosmos API for MongoDB for storage. Uses Azure Developer CLI (azd) to build, deploy, and monitor
todo-python-mongo-aca|Web Application with a Python API and Azure Cosmos DB API for MongoDB on Azure Container Apps|A complete ToDo app with Python FastAPI and Azure Cosmos API for MongoDB for storage. Uses Azure Developer CLI (azd) to build, deploy, and monitor
todo-python-mongo-swa-func|Web Application with a Python API and Azure Cosmos DB API for MongoDB on Static Web Apps and Functions|A complete ToDo app with Python FastAPI and Azure Cosmos API for MongoDB for storage. Uses Azure Developer CLI (azd) to build, deploy, and monitor

**Comment by weikanglim** [comment] 2023-02-23 01:29
@gkulin Thanks for looking through it. 

I did mean 150 characters, not words 😆. The specification [here](https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main#supported-metadata-fields-for-readmemd) mentioned no more than 150. On the cards, I do notice some truncation at ~160

**Comment by weikanglim** [comment] 2023-03-01 19:13
Looks like we still need:
1. Merge templates from `staging` -> `master`
2. Submit the onboarding form for each template
3. Wait for them to publish and verify what it looks like on the review site

**Comment by weikanglim** [comment] 2023-03-14 22:48
Submitted onboarding requests for each template

Should see the changes in `staging` tomorrow.

**Comment by rajeshkamal5050** [comment] 2023-03-23 06:48
Completed as part of #425

**Closed by rajeshkamal5050** 2023-03-23 06:48 UTC
Labels: documentation, feature, templates
