### ISSUE TITLE
[Issue] Static Web App claims to deploy, but doesn't actually

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#1847] opened 2023-04-02 14:45 UTC
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

Whatever is installed in Github action

**Describe the bug**

For this repo:
https://github.com/pamelafox/pamelafox-site/

`azd up` locally seems to work as expected. However, the action doesn't.
It claims it deployed but the website has old content.

See https://github.com/pamelafox/pamelafox-site/actions/runs/4589196674/jobs/8103920293
I outputted the top lines of one of the HTML files, and it seems updated, but the website doesnt reflect it.

So I turned on --debug in the commit after:
https://github.com/pamelafox/pamelafox-site/actions/runs/4589218345/jobs/8103957288

I notice this in the logs:
- Preparing deployment. Please wait...
✖ An unknown exception has occurred

So I wonder if its silently failing but thinking it worked.

**To Reproduce**

Fork, azd pipeline config, azd up, git push.

**Comment by rajeshkamal5050** [comment] 2023-04-13 19:24
@wbreza @hemarina 

Looking at the logs from https://github.com/pamelafox/pamelafox-site/actions/runs/4589218345/jobs/8103957288
- SWA CLI isn't giving proper exit codes for Azd to handle after `An unknown exception has occurred`? 
```
2023/04/02 14:31:57 deploy.go:164: - Publishing deployment artifacts...
2023/04/02 14:31:57 command_runner.go:88: Run exec: 'npx -y @azure/static-web-apps-cli@1.0.0 deploy --tenant-id *** --subscription-id *** --resource-group ***-rg --app-name ***hrcsdnknmolim-swa --app-location ./src --output-location flaskapp/build --env default --no-use-keychain --deployment-token <redacted>'
2023/04/02 14:32:34 service_target_staticwebapp.go:73: 
Welcome to Azure Static Web Apps CLI (1.0.0)

Deploying front-end files from folder:
  /__w/pamelafox-site/pamelafox-site/src/flaskapp/build


Deploying to environment: default


Found configuration file:
  /__w/pamelafox-site/pamelafox-site/src/staticwebapp.config.json

Deploying project to Azure Static Web Apps...
Could not find StaticSitesClient local binary
- Downloading https://swalocaldeploy.azureedge.net/downloads/1.0.022431/linux/StaticSitesClient@1.0.022431
[swa] ✔ Downloading https://swalocaldeploy.azureedge.net/downloads/1.0.022431/linux/StaticSitesClient@1.0.022431
- Preparing deployment. Please wait...
✖ An unknown exception has occurred

2023/04/02 14:32:34 main.go:46: Retry: =====> Try=1
2023/04/02 14:32:34 main.go:46: Authentication: *azidentity.ClientAssertionCredential.GetToken() acquired a token for scope https://management.core.windows.net//.default

2023/04/02 14:32:34 main.go:46: Request: ==> OUTGOING REQUEST (Try=1)
   GET https://management.azure.com/subscriptions/***/resourceGroups/***-rg/providers/Microsoft.Web/staticSites/***hrcsdnknmolim-swa/builds/default?api-version=2021-03-01
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armappservice/v1.0.0 (go1.20; linux),azdev/0.7.0-beta.1 (Go go1.20; linux/amd64) GhActions

2023/04/02 14:32:34 deploy.go:164: - Verifying deployment...
2023/04/02 14:33:17 main.go:46: Response: ==> REQUEST/RESPONSE (Try=1/43.424958985s, OpTime=43.424979486s) -- RESPONSE RECEIVED
   GET https://management.azure.com/subscriptions/***/resourceGroups/***-rg/providers/Microsoft.Web/staticSites/***hrcsdnknmolim-swa/builds/default?api-version=2021-03-01
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armappservice/v1.0.0 (go1.20; linux),azdev/0.7.0-beta.1 (Go go1.20; linux/amd64) GhActions
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
```

**Comment by pamelafox** [comment] 2023-04-13 21:59
Ah the predeploy script creates that build folder. But maybe that needs to be a different hook now? I haven't tried it with the latest azd. I can try in a few days.

**Comment by vhvb1989** [comment] 2023-04-13 22:51
> Ah the predeploy script creates that build folder. But maybe that needs to be a different hook now? I haven't tried it with the latest azd. I can try in a few days.

Yes, `predeploy` is kind of useless now... @rajeshkamal5050 @wbreza , what if we just remove that hook?  It will just continue to bring more issues like this...  

@pamelafox , I created a PR to fix your template: https://github.com/pamelafox/pamelafox-site/compare/main...vhvb1989:pamelafox-site:patch-1

**Comment by rajeshkamal5050** [comment] 2023-04-18 06:05
> Yes, `predeploy` is kind of useless now... @rajeshkamal5050 @wbreza , what if we just remove that hook? It will just continue to bring more issues like this...

I believe there could be other predeploy use-cases that users would want to leverage it.

Thanks @vhvb1989 for the fix. Closing this issue.

**Comment by pamelafox** [comment] 2023-04-18 19:26
I don't believe the original issue is fixed? My repo is now up to date with latest azd, but I still see the exception in the workflow, and my site doesn't seem updated.

Latest workflow:
https://github.com/pamelafox/pamelafox-site/actions/runs/4736150372/jobs/8407302484

**Comment by rajeshkamal5050** [comment] 2023-04-18 19:38
> I don't believe the original issue is fixed? My repo is now up to date with latest azd, but I still see the exception in the workflow, and my site doesn't seem updated.
> 
> Latest workflow: https://github.com/pamelafox/pamelafox-site/actions/runs/4736150372/jobs/8407302484

@wbreza is this due to #1953 and we don't support swa-cli-config.json?

**Comment by wbreza** [comment] 2023-04-18 19:47
> > I don't believe the original issue is fixed? My repo is now up to date with latest azd, but I still see the exception in the workflow, and my site doesn't seem updated.
> > Latest workflow: https://github.com/pamelafox/pamelafox-site/actions/runs/4736150372/jobs/8407302484
> 
> @wbreza Wallace Breza FTE is this due to #1953 and we don't support swa-cli-config.json?

@rajeshkamal5050 , @pamelafox - azd did likely deploy "something" but not was was intended.  Since we currently do not support the usage of `swa-cli-config.json` the output/dist folder would not be populated with the required static content for the SWA app function correctly.

The workaround for the time being is to execute the SWA app build command manually within an azd `prepackage` hooks that prepares the output folder with the bits that should be deployed.  At this point the SWA CLI should be able to do the right thing.

@vhvb1989 - I agree with @rajeshkamal5050 here that the `predeploy` hook could have many other valuable use cases and should remain available.

**Comment by pamelafox** [comment] 2023-04-18 19:49
Hm, I'm confused as to why it works okay locally but not within the action? What's different?

**Comment by wbreza** [comment] 2023-04-18 19:51
> Hm, I'm confused as to why it works okay locally but not within the action? What's different?

@pamelafox did you run any other commands locally prior to `up` that could have prepped the output/dist folder with the correct content?

**Comment by pamelafox** [comment] 2023-04-18 20:06
Ah so locally I run `azd up`, which calls the prepackage hook that populates the directory. The standard workflow calls provision followed by deploy, so I suppose it doesn't have an opportunity to call the hook. Perhaps I could change the workflow to just call up? Or will that break in some way?

**Comment by wbreza** [comment] 2023-04-18 22:14
@pamelafox It depends on how you have the hooks wired up.  The `package` command hook runs in the `azd up` flow but wouldn't run when calling `azd provision` followed by `azd deploy`.  

If you registered them as service hooks then the `package` hooks would run in both scenarios.

Looking at your github action run it looks like the hook is firing but may be throwing an error?
https://github.com/pamelafox/pamelafox-site/actions/runs/4736150372/jobs/8407302484#step:7:87

**Comment by vhvb1989** [comment] 2023-04-18 22:40
Here's an example:

![image](https://user-images.githubusercontent.com/24213737/232920011-5a07a429-c9c7-4d24-87fb-47d2aa93e425.png)


Running `npx -y @azure/static-web-apps-cli@1.0.6` , then doing `ctr+c` to interrupt the and kill the process, then checking the last process' return code is `0`..   

For azd, we must do regex match for npx output to figure if there was a fail?

**Comment by vhvb1989** [comment] 2023-04-19 03:12
Used some more time to debug what's happening.

When running on GitHub Actions **only**, the swa-cli returns an error if it finds the `staticwebapp.config.json` in the app /src folder.
I created a PR for your repo @pamelafox https://github.com/pamelafox/pamelafox-site/pull/25 to temporally disable the settings file.  I tested on my side that running on CI build works.

I think we need to update the `deploy` command we use on azd for the swa-cli and pass only the package output folder, and not the source app...  My theory is that, on CI, the swa cli is trying to build the app if it find the settings file,

**Comment by rajeshkamal5050** [comment] 2023-04-19 16:40
- For Gallium #1953
- For GA, if the hooks workaround works fine. Lets document it as a known issue and the workaround we did.

**Comment by vhvb1989** [comment] 2023-04-19 18:13
@rajeshkamal5050 I verified the todo templates with `swa` and we have this same issue there.  
I tried on latest release and daily.
Deploying on CI builds (github actions) does not work for `wsa` if there is a `staticwebapp.config.json` file.  The CI error is:

![image](https://user-images.githubusercontent.com/24213737/233163450-b7f65255-0888-4013-abb0-255062cdf97e.png)

Talked to @wbreza and we need to fill an issue and follow up with the SWA team.

@savannahostrowski , FYI

**Comment by vhvb1989** [comment] 2023-04-20 19:54
Found out root cause and filled swa-cli issue: https://github.com/Azure/static-web-apps-cli/issues/688

Created PR for Pamela's site.

Pending to create fix for out todo-swa templates

**Comment by gkulin** [comment] 2023-05-10 19:42
documenting this as known issue w/ workaround: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4455

**Comment by pamelafox** [comment] 2023-05-10 20:58
Just wanted to make sure you know that the TODO apps still need a workaround. (I don't think that's tracked anywhere else).

**Comment by savannahostrowski** [comment] 2023-05-10 21:02
@pamela

**Comment by wbreza** [comment] 2023-05-15 20:28
> Just wanted to make sure you know that the TODO apps still need a workaround. (I don't think that's tracked anywhere else).

@pamelafox What are you referring to exactly?  Our Todo templates provision and deploy as expected using the static web app variants. We are using a slightly different method of generating the required environment configurations that leverages a `predeploy` hook to build a JavaScript configuration file that is then copied to the build output folder.

**Comment by pamelafox** [comment] 2023-05-15 20:30
A few comments ago, @vhvb1989 said this was an issue for the TODO templates as well:
https://github.com/Azure/azure-dev/issues/1847#issuecomment-1515165904
I haven't looked into their hooks myself, I was just going on what Victor said.

**Comment by wbreza** [comment] 2023-05-15 20:34
I believe @vhvb1989 fixed the issue with the SWA cli error... I'll let him comment here.

**Comment by vhvb1989** [comment] 2023-05-16 01:46
the issue is not fixed, I just added a workaround and opened an issue for swa-cli: https://github.com/Azure/static-web-apps-cli/issues/688

The issue is still open and the swa-cli team is asking to keep using the workaround for now.

The workaround is:
- Updating the build script to manually copy the `staticwebapp.config.json` to the build folder before calling swa-cli

swa-todo-templates has this workaround.

**Comment by rajeshkamal5050** [comment] 2023-05-16 03:00
Thanks @vhvb1989 

Being a core SWA CLI issue https://github.com/Azure/static-web-apps-cli/issues/688 with workaround for todo templates in place via #2002 and same has been documented for any new external template users https://github.com/Azure/azure-dev/issues/1847#issuecomment-1542711058

Can we close this @vhvb1989 @pamelafox ?

**Closed** 2023-05-16 04:30 UTC
Labels: bug, templates, swa, upstream deps
