### ISSUE TITLE
[Feature Request] CI support for exposed services

### ISSUE THREAD

**Issue by MiTschMR** [Azure/azure-dev#3248] opened 2024-01-28 11:46 UTC
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.5.1 (commit 3856d1e98281683b8d112e222c0a7c7b3e148e96)

**Describe the feature request**
Currently there is no way for setting the environment's `config.json` file values during a CI pipeline with GitLab regarding e.g. the exposed services, like this: 
```json
{
  "services": {
    "app": {
      "config": {
        "exposedServices": [
          "xyz-api"
        ]
      }
    }
  }
}
```

The exposed services are asked when calling the `azd provision` command and there is nothing set yet in the `config.json` file for that environment. My workaround so far is by adding these entries to the `.gitignore` in order to still have the config file during my pipeline: 
```
!.azure
.azure/config.json
```

This way the contents of the `.azure` directory is still excluded. It would be great if we could specify these settings in a possible environment variable or as a command parameter.

**Comment by ellismg** [comment] 2024-01-29 18:34
We've been talking about this with the Aspire team and we expect the design will improve in Preview 4.  It is our intention to make it possible to express in the AppHost project if a service is external or not - which will remove the need for `azd` to track this information and for you to check it in.  We think that's the clearer design (and expresses your intention in the app model itself, instead of in each tool that deploys the app)

What you have is the best we can do for now.

We also do expect to add some UI to manage the environment's `config.json`, but that is also likely a month or so out.  With Aspire making the above change - that's what we are going to focus on now.

**Comment by rajeshkamal5050** [comment] 2024-02-06 17:51
Duplicate of,
- https://github.com/dotnet/aspire/issues/2099
- https://github.com/Azure/azure-dev/issues/3284

**Closed by rajeshkamal5050** 2024-02-06 17:51 UTC
Labels: question, customer-reported
