### ISSUE TITLE
[Feature] Support gradle for Java project

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-dev#2702] opened 2023-09-04 09:14 UTC
Currently AZD CLI for Java projects only supports using maven to package. Will it support gradle as well? So far for gradle projects, we have to convert them to maven then make them AZD templates.

**Comment by savannahostrowski** [comment] 2023-09-05 17:55
Closing as dupe of #2705

**Closed by savannahostrowski** 2023-09-05 17:55 UTC
