### ISSUE TITLE
[Issue] AZD Deploy Throws ArgumentNullException FromSystem.IO.BinaryWriter.Write()

### ISSUE THREAD

**Issue by sb-chericks** [Azure/azure-dev#4385] opened 2024-09-27 18:08 UTC
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.10.1 (commit 31409a33266fb4a5fdbb644bc83988e725d6c7c9)

**Describe the bug**
Running my Aspire project locally works just great, all containers mount successfully and my 2 API applications run and respond correctly. I have run `azd auth login`, `azd env select MY_ENV_NAME`, and `azd provision` successfully.

However running `azd deploy` throws `System.ArgumentNullException` from `System.IO.BinaryWriter.Write(String value)`. A full dump of the command logs are added below.

Running `azd deploy --debug` for the full debug logs doesn't add any useful information.

**To Reproduce**
I'm not sure how to reproduce this.

**Expected behavior**
Azd successfully deploys the built app to my Azure Environment

**Environment**
Information on your environment:
    * aspire                     8.2.0/8.0.100         SDK 8.0.400, VS 17.10.34825.169, VS 17.11.35312.102
    * Visual Studio - Version 17.11.4

**Additional context**
```
MSBUILD : error MSB4166: Child node "7" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\chericks\AppData\Local\Temp\MSBuildTemp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
MSBUILD : error MSB4166: C:\Users\chericks\AppData\Local\Temp\MSBuildTemp\MSBuild_pid-25732_c7b2ef6c9f844a5587b08fcffa7173cb.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 25732:
MSBUILD : error MSB4166: ====================<redacted>
MSBUILD : error MSB4166: 9/27/2024 10:58:41 AM
MSBUILD : error MSB4166: System.ArgumentNullException: Value cannot be null. (Parameter 'value')
MSBUILD : error MSB4166:    at System.ArgumentNullException.Throw(String paramName)
MSBUILD : error MSB4166:    at System.IO.BinaryWriter.Write(String value)
MSBUILD : error MSB4166:    at Microsoft.Build.Framework.TelemetryEventArgs.WriteToStream(BinaryWriter writer)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.Translate(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ==================<redacted>
MSBUILD : error MSB4166:
MSBUILD : error MSB4166:
Build failed. Properties, Items, and Target results cannot be obtained. See details in stderr above.
```

**Comment by rajeshkamal5050** [comment] 2024-09-27 18:24
@sb-chericks thanks for reporting.

@vhvb1989 can you check if anything on azd side?

cc @davidfowl @mitchdenny

**Comment by vhvb1989** [comment] 2024-09-27 23:19
@sb-chericks can you share your AppHost code?  It looks like there's some input missing during `deploy`

**Comment by sb-chericks** [comment] 2024-09-30 14:37
Here is the content of my `AppHost/Program.cs`, let me know if you need to see something else. I've redacted my business namespaces and names.
```
using Microsoft.Extensions.Configuration;
using Projects;

const string applicationInsightsIdentifier = "ApplicationInsightsTelemetry";

var builder = DistributedApplication.CreateBuilder(args);
IResourceBuilder<IResourceWithConnectionString> identityDatabaseResource;
IResourceBuilder<IResourceWithConnectionString> applicationInsightsTelemetryResource;

if (builder.ExecutionContext.IsRunMode)
{
    builder.Configuration.AddUserSecrets<Program>();

    identityDatabaseResource = builder.AddSqlServer(
            "identity-context",
            builder.AddParameter("LocalDatabasePassword", true))
        .WithDataVolume("identityContextVolume").AddDatabase(Constants.IdentityContextIdentifier);

    applicationInsightsTelemetryResource = builder.AddConnectionString(
        applicationInsightsIdentifier,
        "APPLICATIONINSIGHTS_CONNECTION_STRING");
}
else
{
    identityDatabaseResource = builder.AddConnectionString(Constants.IdentityContextIdentifier);

    applicationInsightsTelemetryResource = builder.AddAzureApplicationInsights(applicationInsightsIdentifier);
}

var redisResource = builder.AddConnectionString(Constants.RedisIdentifier);
var gemDatabaseResource = builder.AddConnectionString(Constants.GemContextIdentifier);

var customerPrefetchResource = builder.AddConnectionString(Constants.ServiceBus.CustomerPrefetchSendIdentifier);
var marketingCampaignsResource = builder.AddConnectionString(Constants.ServiceBus.MarketingCampaignsSendIdentifier);

builder.AddProject<My_Business_Aspire_ServerServer>("server-server")
    .WithExternalHttpEndpoints()
    .WithReference(gemDatabaseResource)
    .WithReference(identityDatabaseResource)
    .WithReference(redisResource)
    .WithReference(customerPrefetchResource)
    .WithReference(marketingCampaignsResource)
    .WithReference(applicationInsightsTelemetryResource)
    .WithConfigurationParameters<IdentityConfiguration>()
    .WithConfigurationParameters<CrmConfiguration>()
    .WithConfigurationParameters<DialerConfiguration>()
    .WithConfigurationParameters<GemInstallerConfiguration>()
    .WithConfigurationParameters<DataStoreConfiguration>()
    .WithConfigurationParameters<DoubleBookerConfiguration>()
    .WithConfigurationParameters<GoogleConfiguration>()
    .WithConfigurationParameters<ServerServerConfiguration.ServerServerApplicationConfiguration>()
    .WithConfigurationParameters<ServerServerConfiguration.AzureAdConfiguration>()
    .WithConfigurationParameters<ServerServerConfiguration.QueueNameConfiguration>()
    .WithConfigurationParameters<ServerServerConfiguration.SignalRNegotiateConfiguration>();

// Some configs are being added twice.
// We need to figure out a way to just do it once for both projects.
builder.AddProject<My_Business_Aspire_ClientServer>("client-server")
    .WithExternalHttpEndpoints()
    .WithReference(gemDatabaseResource)
    .WithReference(identityDatabaseResource)
    .WithReference(redisResource)
    .WithConfigurationParameters<GemInstallerConfiguration>()
    .WithConfigurationParameters<DoubleBookerConfiguration>()
    .WithConfigurationParameters<DataStoreConfiguration>()
    .WithConfigurationParameters<GoogleConfiguration>()
    .WithConfigurationParameters<IdentityConfiguration>()
    .WithConfigurationParameters<CrmConfiguration>()
    .WithConfigurationParameters<DialerConfiguration>()
    .WithConfigurationParameters<ClientServerConfiguration.ClientServerApplicationConfiguration>()
    .WithConfigurationParameters<ClientServerConfiguration.CentersDialTimeMinMaxConfiguration>()
    .WithConfigurationParameters<ClientServerConfiguration.AccessTokenConfiguration>()
    .WithConfigurationParameters<ClientServerConfiguration.HostConfiguration>();

builder.Build().Run();

**Comment by sb-chericks** [comment] 2024-09-30 21:00
I'm starting to suspect something is wrong with my `dotnet` installation. I'm running the latest `8.0.4` release, but my work partner was able to run `azd deploy` with my same repository with no problems. The educated guess of my colleague right now is that there is some parallelism issue with the `dotnet build` process that is failing.

I'm going to completely purge and reinstall `dotnet` and see if this helps.

**Comment by rajeshkamal5050** [comment] 2024-10-16 07:36
@sb-chericks any updates?

**Comment by sb-chericks** [comment] 2024-10-16 15:20
Thanks for checking back @rajeshkamal5050.

No, this did not solve the problem. Of my 4 person team, 2 members were able to manually deploy the Aspire project to Azure, while 2 were not.

We are all running the same version of dot net and visual studio, working from the same secrets and app settings, from the same code repository and branch.

It must be some underlying issue with the installation of the software itself, or some artifact in the individual Windows user profile somewhere that is causing the issue.

The two of us that are failing have given up on this endeavor, since we nearly have our azure dev ops pipeline script finished and will be able to rely on that for deployments instead.

If you don't think this is worth pursuing, I can close the issue.

**Comment by rajeshkamal5050** [comment] 2024-10-16 16:41
@sb-chericks suspecting due to this [Update your .NET SDK to 8.0.401. There was a regression with container publish.](https://github.com/dotnet/aspire/issues/5421#issuecomment-2320077379)

Related issues
- https://github.com/dotnet/aspire/issues/6092
- https://github.com/dotnet/aspire/issues/5421

**Comment by mitchdenny** [comment] 2024-10-23 10:27
I think we can close this. The resolution is updating the SDK.

**Closed** 2024-10-23 15:21 UTC
Labels: question, needs-author-feedback, customer-reported, aspire

**Comment by sb-chericks** [comment] 2024-10-23 15:34
Agreed, we can close this. I haven't had time to confirm this was the issue for me, but will next week. My co-worker did confirm it fixed the identical issue for him.

Thanks so much for your help guys.
