### ISSUE TITLE
Unable to download template from private GitHub repo

### ISSUE THREAD

**Issue by mcollier** [Azure/azure-dev#975] opened 2022-10-24 19:56 UTC
**Describe the bug**
Unable to download template from private GitHub repository.

**To Reproduce**
1. Have a private GitHub repository
2. Sign into GitHub using the GitHub CLI.
3. Attempt to execute `azd init` against the private repository (e.g., `azd init --template mcollier/foo --debug`)
4. Observe a continually spinning "Downloading template /" status message.

**Expected behavior**
Template downloads from private repository without error.

**Environment**
Information on your environment:
    * Windows 11 22H2 (OS Build 22623.870)
    * Windows Terminal Preview Version: 1.16.2642.0
    * Azure CLI version 2.41.0
    * GitHub CLI 2.18.1 (2022-10-20)
    * git version 2.38.1
    * azd version 0.3.0-beta.3 (commit a1945858bbeb1090bb2e75d20b3b20e8af182d98)

**Additional context**
![image](https://user-images.githubusercontent.com/1142273/197616145-a691dbe0-fc15-49de-a898-de0d27c291e6.png)

**Comment by weikanglim** [comment] 2022-10-24 21:31
Probably duplicate of #47 that we definitely need to fix, but we haven't been prioritizing high up on the list since we mostly deal with public templates correctly.

@mcollier The workaround in the meantime is to first run  `gh repo clone`, or `git clone` (assuming you have a credential manager installed) against the repository to configure git auth. Then, running `azd init` will work as expected.

**Comment by rajeshkamal5050** [comment] 2022-10-25 19:20
Closing this in favor of #47 and moved it to On Deck.

**Closed by rajeshkamal5050** 2022-10-25 19:20 UTC
Labels: bug, templates
