### ISSUE TITLE
`azd down` does not clean up resources after failed deployment

### ISSUE THREAD

**Issue by tpetchel** [Azure/azure-dev#2508] opened 2023-07-11 19:59 UTC
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

```
azd version 1.0.2 (commit 145e046b1ea9394bd4e1b1d539eb32e860d692fb)
```

**Describe the bug**

I found that `azd up` occasionally fails. One of the services fails to come up at random. But that's not the core issue here. 

During troubleshooting, I discovered that `azd down` does not see the resource group is created and therefore does not clean up the partial deployment.

**To Reproduce**

The `azd up` failure happens only on occasion. To reproduce the issue, I started with a script that repeatedly brings the deployment up and down until it fails.

I ran this on macOS; modify as needed.

```
#!/usr/bin/env bash

set -e

rm -rf /tmp/default
mkdir -p /tmp/default
cd /tmp/default

azd init --template https://github.com/Azure-Samples/msdocs-flask-postgresql-sample-app
azd env set AZURE_LOCATION eastus
azd env set AZURE_SUBSCRIPTION_ID $(az account show --query id --output tsv)

while true
do
    echo "Resource group should not exist:"
    az group list --query "[].name" --output tsv | grep default-dev && false || true

    azd up

    echo "Resource group should exist:"
    az group list --query "[].name" --output tsv | grep default-dev && true || false

    azd down

    echo "Resource group should not exist:"
    az group list --query "[].name" --output tsv | grep default-dev && false || true
done
```

You'll need to attend the script while it runs and reply with `y` to the confirmation prompts.

Eventually you'll catch a failed deployment, for example:

```
  (✓) Done: Resource group: default-dev-rg
  (✓) Done: Log Analytics workspace: default-dev-ochogy5totpus-workspace
  (✓) Done: Virtual Network: default-dev-ochogy5totpus-vnet
  (✓) Done: App Service plan: default-dev-ochogy5totpus-service-plan
  (x) Failed: Application Insights: default-dev-ochogy5totpus-appinsights
  (✓) Done: App Service: default-dev-ochogy5totpus-app-service
  (✓) Done: Azure Database for PostgreSQL flexible server: default-dev-ochogy5totpus-postgres-server
```

Next, run `azd down` to tear down the deployment. You'll see that it does not see the resource group and therefore does not clean anything up.

```
$ azd down

Deleting all resources and deployed code on Azure (azd down)
Local application code is not deleted when running 'azd down'.

Resource group(s) to be deleted:


? Total resources to delete: 0, are you sure you want to continue? Yes
Deleting your resources can take some time.



SUCCESS: Your application was removed from Azure in 5 seconds.
```

If you go to the Azure portal or query the resource group from the Azure CLI, you'll see that it's still active. In my case, the resource group is named "default-dev-rg".

```
$ az group list --query "[].name" --output tsv | grep default-dev
default-dev-rg
```

I then need to manually delete the resource group from the command line or the portal.

**Expected behavior**

`adz down` should delete what it provisioned.

**Environment**

* macOS 13.4.1 (22F82)
* `azd` version 1.0.2 
 
**Additional context**

**Comment by ellismg** [comment] 2023-07-12 18:00
Thanks for this super helpful repo, @tpetchel!  The behavior here is very surprising - my guess here is that in this case out logic to discover all the resource groups from the most recent deployment is just wrong.

When we are in this failed case, it would be interesting to look at the most recent deployment object and see why our logic to discover the resource groups from it is failing.

The script you've provided should make it easy for me to reproduce this.  Thanks for including it!

**Comment by ellismg** [comment] 2023-07-22 00:35
Was able to catch a repo of this.

The problem is related to the change we made in #2048, which moved us to using the `outputResources` property of the deployment to discover the resources instead of spelunking around the dependencies and trying to discover resources.

Frustratingly, in the case of a failed deployment, it seems like the output resources are unset (even thought the resource group was created at the subscription level, and many resources were deployed into it).

Here's a sanitized version of the output of `az deployment sub show` for the doomed deployment:
https://gist.github.com/ellismg/f06c62638046ed4559c10fb51fc4615a

While you can see in the portal that many resources were provisioned into the resource group:

![Image](https://github.com/Azure/azure-dev/assets/9602953/cf8785bf-2df0-4533-bee6-6b3055cf481e)

Perhaps when there are no outputs we could fall back to our older strategy of trying to discover the resource groups dependencies?  Per, @weikanglim's investigation which lead to the fix in #2048, this may still fail in the case where the resource group itself is empty (this could happen if the nested deployment fails to create any resources?  Should be possible for us to test this), but we would correctly handle cases like this.

Thanks again, @tpetchel for this wonderful script.  I did make some small modifications (passing `--no-prompt` to both `azd up` and `azd down` and then `--force` and `--purge` to azd down, to prevent me from having to babysit it as much, and I got lucky and it failed on the second iteration, with this error from the RP:

> The value of the 'Version' should be in: []. Verify that the specified parameter value is correct. Click here for details

As a side note, seems bad that the RP failed like this.  The template did not change between the two runs, and the error message having an empty list of supported versions doesn't seem like it's a good thing.

**Comment by weikanglim** [comment] 2023-07-22 18:55
> As a side note, seems bad that the RP failed like this. The template did not change between the two runs, and the error message having an empty list of supported versions doesn't seem like it's a good thing.

It is really not ideal. Having hit this just this week, I believe the actual underlying error is that the postgresql server cannot be deployed to the given region. The mechanism of the failure depended on no "Versions" being available in that particular region.

> Perhaps when there are no outputs we could fall back to our older strategy of trying to discover the resource groups dependencies? Per, @weikanglim's investigation which lead to the fix in https://github.com/Azure/azure-dev/pull/2048, this may still fail in the case where the resource group itself is empty (this could happen if the nested deployment fails to create any resources?

It is unfortunate that we regressed the behavior with failed deployments with #2048. Supposedly if ARM had always provided `outputResources` even for failed deployments, there's a nice property where the client could also avoid deleting resource groups that were never provisioned into due to early exits. I'm not sure what the behavior would look like for relying on dependencies. Nevertheless...

For the overall desired behavior, I suspect we want to clean up all resource groups that were deployed into for a sub-level deployment. Given that `outputResources` is just empty when the deployment fails, using the dependencies makes sense here. Perhaps we can just check for "what are all the resource-group `Microsoft.Deployment`" objects? There's also a chance for us to figure out dependencies between RGs that perhaps satisfies the VNET/resource-related issues. It's quite possible that the dependency graph exists in the ARM deployment.

For a RG-level deployment, I think we'd need to examine the behavior as well.

I see that @ellismg is currently assigned to issue. Let me know if you'd like me to take the issue. Be happy to revisit what the correct deletion logic is here.

**Comment by ellismg** [comment] 2023-07-24 18:50
>> As a side note, seems bad that the RP failed like this. The template did not change between the two runs, and the error message having an empty list of supported versions doesn't seem like it's a good thing.
>
> It is really not ideal. Having hit this just this week, I believe the actual underlying error is that the postgresql server cannot be deployed to the given region. The mechanism of the failure depended on no "Versions" being available in that particular region.

I suspect that is not happening in this case, since I had successfully deployed the same template into the same region in a previous deployment.

> Supposedly if ARM had always provided outputResources even for failed deployments, there's a nice property where the client could also avoid querying for resource groups that were never provisioned into due to early exits. I'm not sure what the behavior would look like for relying on dependencies. Nevertheless...

I agree with this, it would be nice.  I'll send a message to some of the control plane folks but nevertheless indeed...

> For the overall desired behavior, I suspect we want to clean up all resource groups that were deployed into for a sub-level deployment. Given that outputResources is just empty when the deployment fails, using the dependencies makes sense here. Perhaps we can just check for "what are all the resource-group Microsoft.Deployment" objects? 

Yeah, I'll look at reviving some of that code, to run in the case where `outputResources` is null.  Happy to handle this myself, @weikanglim, so you can focus on the fingerprinting stuff.

**Closed** 2023-07-26 18:29 UTC
Labels: bug
