### ISSUE TITLE
Error: no project exists; to create a new project, run `azd init` - when using `azure.yml` instead of `azure.yaml`

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#2381] opened 2023-06-09 05:04 UTC

**Comment by savannahostrowski** [comment] 2023-06-09 20:39
@vhvb1989 This is a bug right?

**Comment by vhvb1989** [comment] 2023-06-11 07:18
@savannahostrowski yes, `.yml` or `.yaml` should be both valid, IMO.
Unless you want to only allow `azure.yaml` by design

**Comment by savannahostrowski** [comment] 2023-06-12 15:07
Yeah I was asking because we have an issue for adding support for .yml already.

https://github.com/Azure/azure-dev/issues/364

**Comment by rajeshkamal5050** [comment] 2023-06-13 16:53
@savannahostrowski @vhvb1989 marking this as a duplicate of #364

**Closed by rajeshkamal5050** 2023-06-13 16:53 UTC
Labels: bug
