### ISSUE TITLE
Deployment status API not reliable for App Service

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#4126] opened 2024-07-15 22:25 UTC
We are seeing more and more instability in our template tests that deploy to app service.

> ERROR: deployment failed: error deploying infrastructure: deploying to subscription:
> Deployment Error Details:
InternalServerError: There was an unexpected InternalServerError.  Please try again later.  x-ms-correlation-request-id: <redacted>

Repro steps:
1. azd init -t todo-nodejs-mongo
2. azd up

Wait for deployment to complete.  Users experience random `InternalServerError` failures.

**Comment by rajeshkamal5050** [comment] 2024-08-21 16:31
@hemarina can you triage this?

**Comment by rajeshkamal5050** [comment] 2024-09-19 00:03
Duplicate of #4093

**Closed by rajeshkamal5050** 2024-09-19 00:03 UTC
Labels: test automation, flaky test, app service
