### ISSUE TITLE
[codespaces] vscode plugin is installed by default but still get prompt to install it

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#916] opened 2022-10-19 14:37 UTC
This probably needs to be routed to someone on vscode team. 

The azd vscode extension is in the `devcontainer.json` file ([example](https://github.com/Azure/azure-dev/blob/main/templates/common/.devcontainer/devcontainer.json/java/devcontainer.json#L20)) yet we sometimes see alerts to install it. 

Repro steps: 
1. Create new codespaces instance of a repo (e.g. https://github.com/Azure-Samples/todo-nodejs-mongo/tree/main) 
2. Wait for creation to finish
3. Observe first run 
![image](https://user-images.githubusercontent.com/2158838/196714897-968ed9f9-26f7-4d56-bc8f-729f95302ef3.png)

Expected: no alert to install azure developer extension
Actual: Alert to install azure developer extension, after the extension is installed

**Comment by weikanglim** [comment] 2022-11-02 19:19
Duplicate of #951

**Closed by weikanglim** 2022-11-02 19:19 UTC
Labels: codespaces
