### ISSUE TITLE
[codespaces] sizing issue - requires higher configuration

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#970] opened 2022-10-24 10:40 UTC
**Describe the issue:**
Individual deploy test error

**Repro Steps:**
1.Run command: ` bash ./test-templates.sh -c false -t <template_name> -b pr/551 `.
2.Change “complete” to “completed” in UI 
3.Run `azd deploy  --service web`  

**Error Message:**

![image](https://user-images.githubusercontent.com/80496810/197507574-1d5863da-55ba-4ea4-bfc8-83ac16952414.png)

**Environment:**
OS: Codespace.
Templates:
https://github.com/Azure-Samples/todo-csharp-sql-swa-func
https://github.com/Azure-Samples/todo-python-mongo-swa-func
Branch: [pr/551](https://github.com/Azure/azure-dev/pull/551)

**Expected behavior:**
Run `azd deploy  --service web`  can run successfully.

@jongio for notification.

**Comment by rajeshkamal5050** [comment] 2022-10-24 16:27
cc: @danieljurek for Codespace environment

**Comment by jongio** [comment] 2022-10-24 16:48
Yes, I ran into this to.  You need to use a bigger codespace spec.  You can go to https://github.com/codespaces/ and change it.

**Comment by danieljurek** [comment] 2022-10-24 17:35
This reads exactly like an out of memory error that we encountered previously. Moving up to an 8GB VM should get you past this problem. We have a PR to move the machine size up by default.

**Comment by zedy-wj** [comment] 2022-10-25 08:57
@jongio, @danieljurek - We have changed the machine size to `4 core 8GB`, but it failed when we executed `bash ./test-templates.sh -c false -t Azure-Samples/todo-csharp-sql-swa-func` this time. The error message was shown as below:
![image](https://user-images.githubusercontent.com/81678720/197730099-41f3e9bf-eb2c-44d7-8574-93ab7b2b3f94.png)

**Comment by rajeshkamal5050** [comment] 2022-10-25 16:10
@weikanglim do you see this issue when running this template in Codespaces?

**Comment by weikanglim** [comment] 2022-10-27 21:35
@zedy-wj That was caused by a separate issue that's now been fixed. Can you verify if everything is working as expected, and close if necessary?

**Comment by zedy-wj** [comment] 2022-10-28 02:17
@weikanglim - We have verified with `4 core 8GB` and this issue is no longer reproduced. Besides, the smallest size we can create now is `4 core 8GB`. We will close it, thanks.

**Closed by zedy-wj** 2022-10-28 02:17 UTC
Labels: codespaces, templates
