### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by DrBoomaPM** [Azure/azure-dev#2363] opened 2023-06-06 06:17 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-dev.views.workspace.application.resolve
Error type: 1
Error Message: Process 'azd show --no-prompt --cwd "c:\Users\b.poolan.mari...' exited with code 1
Error: Error: loading environment: reading environment name: no default response for prompt 'Please enter a new environment name:'

Version: 0.6.0
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.js:2:928019
```

</details>

**Comment by rajeshkamal5050** [comment] 2023-06-06 16:10
Marking this as a duplicate of #2296

**Closed by rajeshkamal5050** 2023-06-06 16:10 UTC
Labels: question, needs-triage, customer-reported
