### ISSUE TITLE
Project dependencies

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#412] opened 2021-10-22 16:12 UTC
Identify how to handle dependencies between projects.

Standard use case
- Solution with 2 apps, frontend + backend.  
- Need to deploy backend changes before frontend, etc.

**Comment by savannahostrowski** [comment] 2022-08-19 23:48
@wbreza Gentle ping 😸. Is this still needed?

**Comment by rajeshkamal5050** [comment] 2022-08-24 06:03
@wbreza @savannahostrowski Closing this as a duplicate of this
- https://github.com/Azure/azure-dev/issues/121

**Closed by rajeshkamal5050** 2022-08-24 06:03 UTC
