### ISSUE TITLE
Support adding custom domains to Aspire apps deployed via ACA

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-dev#3102] opened 2023-12-10 22:47 UTC
Over in the Aspire repo we got this feature request:

https://github.com/dotnet/aspire/issues/1322

This is more of a deployment time concern as the domain you want to apply would be different for each environment that you are deploying into. Custom domain support for publicly exposed endpoints pulls in a few considerations such as support for certificates. I know when I've automated this in the past with Bicep you end up needing to have an Azure DNS domain which you can create your sub domain off so that you can use Bicep to inject the necessary TXT records at deployment to allow auto certificate generation.

**Comment by rajeshkamal5050** [comment] 2023-12-11 19:44
Duplicate of #1765

**Closed by rajeshkamal5050** 2023-12-11 19:44 UTC
