### ISSUE TITLE
[ISSUE]- Resource Group not found when trying to deploy subscription scoped deployment via GitHub Actions.

### ISSUE THREAD

**Issue by AaronSaikovski** [Azure/azure-dev#4478] opened 2024-10-23 06:05 UTC
**Output from `azd version`**
azd version 1.10.3 (commit 0595f33fe948ee6df3da492567e3e7943cb9a733)

**Describe the bug**
When trying to deploy Azure infrastructure using 'subscription scoped' bicep code, it is reporting it cannot find the resource group on the first run.
The first pipeline runs then fails then the resource group is created sometime later.
Then we can rerun the pipeline and it finds the resource group on the second run and then deploys the resources properly.
The Bicep code is subscription scoped and does create the resource group when running azd up locally.

the pipeline code is attached

[azure-dev.txt](https://github.com/user-attachments/files/17485873/azure-dev.txt)

**Comment by vhvb1989** [comment] 2024-10-25 05:31
Can you share the bicep you are using to reproduce?  If you can, please share the bicep files and any parameters you are using for the bicep.

**Comment by AaronSaikovski** [comment] 2024-10-25 05:32
can i share directly with you?



Regards,
Aaron Saikovski

Mob: +61 410 480 971
Email: ***@***.***
Skype: aaron.saikovski
LinkedIn: http://www.linkedin.com/pub/aaron-saikovski/3b/b9/159

________________________________

**Comment by AaronSaikovski** [comment] 2024-10-25 05:35
can you share with you directly if possible?

**Comment by vhvb1989** [comment] 2024-10-25 06:55
> can you share with you directly if possible?

Sure, feel free to add me to a private repo, if you want. I can take a look. 
Or, if you can create simple public repo where you can reproduce the issue (removing any confidential staff), that would be ideal

**Comment by AaronSaikovski** [comment] 2024-10-25 20:32
[files.zip](https://github.com/user-attachments/files/17527330/files.zip)
sure see attached here

**Comment by AaronSaikovski** [comment] 2024-11-03 22:14
please see atttached files in thread

**Comment by rajeshkamal5050** [comment] 2024-11-04 17:36
@v-xuto can you triage the repro above and update findings? cc @vhvb1989

**Comment by Menghua1** [comment] 2024-11-05 07:52
@AaronSaikovski This problem occurs because there is no dependency defined between the rsg module and other modules in the `main.bicep` file. Therefore, the Resource Group and other resources (such as key vault) are created at the same time. When the key vault is being created, the resource group has not yet been created. At this time, `the Resource group could not be found` message is reported. The suggestions are as follows:

- Refer to [todo-csharp-sql](https://github.com/Azure-Samples/todo-csharp-sql/blob/main/infra/main.bicep#L50-L67), change the `module rsg` to `resource rsg`, and then change the `scope` value of each other module to `rsg`, as shown below:
![Image](https://github.com/user-attachments/assets/2283aeec-b900-4aa3-820d-d915bfab4b34)

**Comment by AaronSaikovski** [comment] 2024-11-05 23:00
Thanks thats a weird issue but it seems to have been fixed. thanks


Regards,
Aaron Saikovski

Mob: +61 410 480 971
Email: ***@***.***
Skype: aaron.saikovski
LinkedIn: http://www.linkedin.com/pub/aaron-saikovski/3b/b9/159

________________________________

**Comment by Menghua1** [comment] 2024-11-06 02:56
@AaronSaikovski If you are sure that this issue has been resolved, I will close it.

**Comment by AaronSaikovski** [comment] 2024-11-06 02:57
yes please

Regards,
Aaron Saikovski

Mob: +61 410 480 971
Email: ***@***.***
Skype: aaron.saikovski
LinkedIn: http://www.linkedin.com/pub/aaron-saikovski/3b/b9/159

________________________________

**Closed** 2024-11-06 02:58 UTC
Labels: question, needs-triage, needs-author-feedback, customer-reported
