### ISSUE TITLE
[Issue] Unable to use 'old style' Azure Devops Organisations URI (orgname.visualstudio.com)

### ISSUE THREAD

**Issue by Mu4all** [Azure/azure-dev#2784] opened 2023-09-25 19:21 UTC
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.3.1 (commit b5030da0f29ffe98664c40450187fd8a4cb0d157)

**Describe the bug**
Unable to use 'old style' Azure Devops Organisations. Our org still used the **orgname.visualstudio.com** syntax instead of the **dev.azure.com** new style.

In **cli\azd\pkg\pipeline\azdo_provider.go** line 421 it states

`var azdoRemoteHttpsUrlRegex = regexp.MustCompile(`^https://[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*:*.+@dev.azure\.com/(.*?)$`)`

This causes an error to be thrown when trying to run the `azd pipeline config --provider azdo` statement on an otherwise fine target.

**To Reproduce**
See above

**Expected behavior**
I expect old style url's to be accepted

**Environment**
Irrelevant

**Additional context**
None

**Comment by rajeshkamal5050** [comment] 2023-09-25 19:26
@vhvb1989 seems similar to #1072 how big of a change is this?

**Comment by bmallen1** [comment] 2024-01-02 22:13
Hello, I'm also running into this issue.

azd cli version 1.5.1

error message after entering PAT:
ERROR: ensuring git remote: existing remote is not an Azure DevOps host

git remote url:
https://dev.azure.com/organization/Project/_git/ProjectRepo

**Comment by rajeshkamal5050** [comment] 2024-03-07 04:08
Marking this as a duplicate of #1072

**Closed by rajeshkamal5050** 2024-03-07 04:08 UTC
Labels: question, azdo, pipelines, customer-reported, needs-team-attention
