### ISSUE TITLE
Prompting for parameters during provisioning is not working

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#1191] opened 2022-11-18 19:48 UTC
@pamelafox , azd is expected to prompt for the value.  Using `main.parameters.json` is just a way to map the parameter to some value from the environment.
I reviewed the implementation and there's currently a bug because azd is hiding the prompt behind the spinner:

![image](https://user-images.githubusercontent.com/24213737/202788727-f7101cfe-de59-4aff-a37e-e134fa215fac.png)

This also makes `Compiling Bicep template` to never ends, because it stays waiting for a value.

You can work around this (while the issue is fixed) by using `-o json` when running `azd provision`.  This will disable the progress spinner and let you see the prompt:

![image](https://user-images.githubusercontent.com/24213737/202789260-07e838e1-26b6-4638-aff5-06b85e98c026.png)

You can also continue using `main.parameters.json` to map the param to some value within your environment (which might be usually better as it would let you set the value in your env (or per azd environment) instead of getting the prompt.  However, if the value is not set in the environment, we should get the prompt.

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-dev/discussions/906#discussioncomment-4180137_

**Comment by weikanglim** [comment] 2022-11-18 22:07
Duplicate of #1176?

I believe this would be covered in the upcoming environment rework.

**Comment by vhvb1989** [comment] 2022-11-18 22:47
> Duplicate of #1176?
> 
> I believe this would be covered in the upcoming environment rework.

Let me keep this issue opened and expand it for defining what is the expectation when:
- Add a parameter `foo` in bicep w/o adding it to the `main.properties.json` 
  - Note: prompt for a value here.  If azd offers to persist the value in the environment, azd needs to create the mapping in `main.properties.json` ??  
- Add a parameter `foo` in bicep and creating a mapping in `main.properties.json` to env var `BAR`. Then:
  - BAR is set in azd environment
  - BAR is set in azd environment and in System environment
  - BAR is only set in System environment
  - BAR is not set. Neither azd environment nor system environment.
    - NOTE: azd is currently setting an empty string as the result of `env.getenv()` , disabling the prompt for a value
    - Note: prompt for value here. Then saved it in azd environment?

**Closed** 2022-11-24 02:40 UTC
Labels: needs-triage
