### ISSUE TITLE
Add support for surfacing `write-debug` output from PowerShell hook scripts

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-dev#2453] opened 2023-06-22 23:33 UTC
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

I want to facilitate debugging my PowerShell hook scripts without adding a bunch of "Write-Host" statements to them. 

Natively in PowerShell I can add `Write-Debug` statements to my script and by default I won't see them when my script runs. But, if I run `$DebugPreference='Continue'` and then run my script I will see the output from the `Write-Debug`

**To Reproduce**
Example script test.ps1
```
write-host "Hello World!"
Write-Debug "Debug message"
Write-Host "Goodbye World!"
```

Example output
![image](https://github.com/Azure/azure-dev/assets/74415662/3c79b064-f388-4d4a-aaf5-2d47c447703a)

**Expected behavior**
At a minimum, when I set `$DebugPreference='Continue'` at my command line (or in my hook script) and run `azd up --debug` I would like to see the debug output from the hook script included in the azd debug output.

As a mild stretch, if I have `$DebugPreference='Continue'` set at my command line and I run `azd up` without `--debug` I'd still like to see the debug output from the hook script.

As a big stretch, $DebugPreference supports a number of other options: [Break, Ignore, Inquire, Stop, Suspend] and it would be interesting to think whether and how azd should support any of those.

**Comment by rajeshkamal5050** [comment] 2023-07-10 16:48
Seems to be a duplicate of #2432

**Closed by rajeshkamal5050** 2023-07-10 16:48 UTC
Labels: needs-triage
