### ISSUE TITLE
Deployment is not valid according to the validation procedure in todo-nodejs-mongo-swa-func

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-dev#654] opened 2022-09-13 13:13 UTC
**Describe the issue:**
Create resource failed when execute command `azd up`.

**Repro Steps:**
1. Execute command `az login --use-device-code`
2. Execute command  `bash  ./test-templates.sh -c false -t todo-nodejs-mongo-swa-func -b staging`.
3. Execute command `azd env new`
4. Execute command `azd up`

**Error Message:**
![image](https://user-images.githubusercontent.com/57166602/189908654-1d0b9420-919d-4783-97e0-87e9c3a379b6.png)

**Environment:**
CodeSpace
Template: `todo-nodejs-mongo-swa-func`

**Expected behavior:**
Create resource with the command: `azd up` can success.

@jongio for notification.

**Comment by rajeshkamal5050** [comment] 2022-09-14 15:36
Duplicate of #656

**Closed by rajeshkamal5050** 2022-09-14 15:36 UTC
