### ISSUE TITLE
[Issue] AZURE_LOCATION as an environment variable is not honored in Aspire/ACA deploy

### ISSUE THREAD

**Issue by timheuer** [Azure/azure-dev#3031] opened 2023-11-28 20:27 UTC
Sample repo: https://github.com/timheuer/new-aspire-starter

 
Failed run: https://github.com/timheuer/new-aspire-starter/actions/runs/7014845418/job/19083198327#step:10:28
 
Deploy fails here.  I had assumed that AZURE_LOCATION being set as an environment variable would suffice.  When I force check-in an .env file in a folder in .azure/<envname> it works, but using an actual environment variable is not working.

The default `.gitignore` for `azd` seems to be to exclude `.azure` so force checking this in might be problematic and also may contain other env vars that shouldn't be -- e.g. tools like GitGuardian, etc. will flag this checkin.

**Comment by ellismg** [comment] 2023-11-28 21:22
Yes - we don't want the `.azure` folder being checked in today, so we need to figure out what to do here.

There is another piece of "config" that we need to ensure we persist during `pipeline config`, which is the set of aspire services which should have public ingress.  Today that's store as a property in the `config.json` in the environment folder.  Without that, we will treat all services as private, I think, which is unexpected.

**Comment by timheuer** [comment] 2023-11-28 21:34
Yeah @ellismg I also logged https://github.com/Azure/azure-dev/issues/3027 on that one (config.json for exposed services)

**Comment by vhvb1989** [comment] 2023-11-29 04:38
@timheuer , I noticed you are using

```
working-directory: ./new-aspire-starter.AppHost/
```

The azd-project (azure.yaml) is created within `new-aspire-starter.AppHost` folder.  Provision is recognizing the AZURE_LOCATION and creating the infrastructure, but when `deploy` runs from the parent folder, azd is not finding any project there.

azd looks for projects on parent folders (not children).

I think you created this other issue: https://github.com/Azure/azure-dev/issues/3024 which looks like the root cause for the issues you are getting on CI (as side effect).

The `azure.yaml` must be at the root of your project, at the same level of `.github`

**Comment by timheuer** [comment] 2023-11-29 04:48
For Aspire we are running the `azd init` command at the apphost directory so the azure.yml files are being created there for me.

I'm emulating what I'm doing in the desktop environment which works fine doing this pattern.

Where do you see deploy running from the parent folder (I've set working-directory there as well)?

**Comment by timheuer** [comment] 2023-11-29 05:17
Ok, FYI @vhvb1989 I moved things around to the repo root and things still work, but this bug (AZURE_LOCATION) still fails without checking in the .azure contents as @ellismg acknowledges here.

**Comment by vhvb1989** [comment] 2023-11-29 05:25
I apologize, @timheuer , I've reviewed this further and the issue is due to the azd-generated bicep files are missing the  `output AZURE_LOCATION string = location`

When azd runs on CI, it relies on the bicep outputs (deployment outputs) to re-construct an environment, as the outputs are saved to the azd-env (.env).

This is actually not an Aspire-specific issue, it is only visible to aspire b/c most azd-templates are setting the location (and any other value required during deploy) as deployment outputs. So, by the time provision finishes, the .env contains what is required.

I see 2 ways to fix this issue:
  1) Make bicep-provider to persist sub-id and location before starting the deployment. If the iac defines sub-id and location as output, it will be overriden, but it should be fine.

  2) Make azd to produce bicep for aspire which contains sub-id and location as outputs to follow the same model as other templates.

My preference is 1).
@ellismg , what do you think?

**Comment by vhvb1989** [comment] 2023-12-01 20:38
I'd love to use the env-config, but it has a limitation we haven't resolved when you work with more than one device.

For example, if I run `azd up` on my local device A, and I pick the env-name `Foo`, azd can store location to env-config and complete all the process just fine.
Then, if I go to my device B and I run `azd init -e Foo` (to create a azd-env with the same name as in device A) and then I run `azd env refresh` (to pull the outputs from last deployment). The location is going to be missing, so If I run `deploy`, something will go wrong, and if I run `provision`, azd will ask me for the location again (even I have already provided during azd env refresh).
We don't have a way yet to re-construct env-config (other than setting remote-env for azd).

I've been thinking on designing some sort of  `azd env export`, to produce a unique binary file like `azdenv.azd` and `azd env inport` which can take the binary file and reconstruct the environment and config.
This would be a manual alternative to remote-environments, where user can handle his env on a usb-drive :)

**Closed** 2023-12-06 23:15 UTC
Labels: aspire
