### ISSUE TITLE
Improve error diagnostics to help know what to resolve

### ISSUE THREAD

**Issue by timheuer** [Azure/azure-dev#104] opened 2022-07-14 20:10 UTC
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 0.0.1-beta.1614610 (commit 4d3efcfa5779c24a11379ff53102c3fded786e2e)

**Output from `az version`** 
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-dev": "0.0.1b1539385",
    "containerapp": "0.3.7"
  }
}

**Describe the bug**
I created the C# todo template and did `azd up` -- this is the resulting output:
```
Created Azure resources
Error: Command Failed: deployment failed: failed deploying: failed running az deployment sub create:

Deployment Error Details:
InternalServerError: There was an unexpected InternalServerError.  Please try again later.  x-ms-correlation-request-id: 52b6e46e-b887-4323-97f4-924f6284c348
```
The error isn't helpful for me what do know what to do now. Do I run the command again? Do I use the correlation ID to look in portal?

**Comment by rajeshkamal5050** [comment] 2022-08-04 07:17
@timheuer did you retry? were you able to proceed further?

@jongio @savannahostrowski 
Moving it to On Deck. We can pull it into our current milestone based on any further updates.

**Comment by timheuer** [comment] 2022-08-04 13:52
No I have not been successful

-th
________________________________

**Comment by vhvb1989** [comment] 2022-08-17 17:24
The root cause here was an old `azd` version installed with npm globally.  npm was the way to install `azd` in the past, and with the new installers, a system can ended up with two `azd` versions.

Running `npm uninstall -g @azure/az-dev-cli` helps to remove the old version.

The second issue is related to [using upper case for the azd env name](https://github.com/Azure/azure-dev/issues/477), which is WIP and targeted to be part of `version 0.1.0-beta.5` on 8/24.

**Comment by jongio** [comment] 2022-08-17 19:57
@timheuer you got this working right?

**Comment by rajeshkamal5050** [comment] 2022-08-30 05:06
@vhvb1989 and @wbreza worked with @timheuer offline to get this resolved.

Closing this. @timheuer please reopen, if need be.

**Closed by rajeshkamal5050** 2022-08-30 05:06 UTC
