### ISSUE TITLE
Prompt "not logged on" in pipeline log for ASA-Samples-Event-Driven-Application

### ISSUE THREAD

**Issue by blow-hey** [Azure/azure-dev#2269] opened 2023-05-19 10:07 UTC
**Describe the issue:**
Execute alone command  `azd pipeline config --auth-type client-credentials` failed in Github pipeline test.

The error message as follows:
![image](https://github.com/Azure/azure-dev/assets/112381413/17690b13-93ec-4621-9ce4-28556a667356)

**Repro steps:**

1. Run `azd auth login`
2. Run `azd init -t ASA-Samples-Event-Driven-Application`
3. Run `azd pipeline config --auth-type client-credentials`

**Environment:**
OS: Windows desktop, MacOS desktop, Linux desktop, WSL, DevContainer in VS Code and CodeSpace.
Template: ASA-Samples-Event-Driven-Application
Branch: main
Azd version: 0.9.0-beta.2-daily.2786873 (commit de89effa931a89e8125e520e5bc3ff473f014fb5)

**Expected behavior:**
Run command `azd pipeline config --auth-type client-credentials` success.

@rajeshkamal5050 for notification.

**Comment by weikanglim** [comment] 2023-05-19 15:03
@blow-hey Please to link a specific build run so we can triage faster.

From the screenshot above, none of the "Log in" tasks ran, thus `azd` was not logged in on CI, and the failure is expected. The question is:

1. Is the workflow definition incorrect?
2. Or did `pipeline config` not set the required variables?

We could  probably consider updating the default workflow definition to force one auth or another, and not skip both if both types of credentials are unset for a better error-handling experience.

**Comment by rajeshkamal5050** [comment] 2023-05-19 15:50
Nice catch @weikanglim 

@yiliuTo @fangjian0423 
Looks like it works fine with federated credentials. [Needs](https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application/blob/main/.github/workflows/azure-dev.yml) change from vars to secrets to make client-credentials work - https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application/blob/main/.github/workflows/azure-dev.yml

Refer to https://github.com/Azure-Samples/todo-python-mongo/blob/main/.github/workflows/azure-dev.yml

**Comment by yiliuTo** [comment] 2023-05-22 02:04
Hi @rajeshkamal5050 , thanks for helping find the cause and solution. Besides, since we changed the GitHub action config from secrets to vars given this issue: https://github.com/Azure/azure-dev/issues/2143#issuecomment-1540538438, then if I now change it back to secrets, will it break https://github.com/Azure/azure-dev/issues/2143 again?

**Comment by weikanglim** [comment] 2023-05-22 15:27
@blow-hey `secrets.AZURE_CREDENTIALS` is the expected value. See the workflow definition we provide in templates [here](https://github.com/Azure/azure-dev/blob/ddf58ea723bf5526cc1a65362787785e6c366722/templates/common/.github/workflows/bicep/azure-dev.yml#L28)

**Comment by rajeshkamal5050** [comment] 2023-05-22 15:47
> Hi @rajeshkamal5050 , thanks for helping find the cause and solution. Besides, since we changed the GitHub action config from secrets to vars given this issue: [#2143 (comment)](https://github.com/Azure/azure-dev/issues/2143#issuecomment-1540538438), then if I now change it back to secrets, will it break #2143 again?

No @yiliuTo it will not break. 

Previously, we had all of them as secrets. The change should have been to convert secrets to vars excluding `AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}`. But everything was changed to vars which is a bug and will not work for the `azd pipeline config --auth-type client-credentials`.

You can try this `azd pipeline config --auth-type client-credentials` before and after fix.

**Comment by yiliuTo** [comment] 2023-05-23 02:13
@rajeshkamal5050 , thanks for the detailed explanation. This will be fixed by PR: https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application/pull/8

**Comment by yiliuTo** [comment] 2023-05-24 05:22
@rajeshkamal5050 I would like to close this issue since the fix has been merged, please reopen it if the issue still exists.

**Closed by yiliuTo** 2023-05-24 05:22 UTC
Labels: bug, templates
