### ISSUE TITLE
[WebToolsE2E][Aspire Deployment] aspire-dashboard takes too long and errors

### ISSUE THREAD

**Issue by vmykagapuz** [Azure/azure-dev#4216] opened 2024-08-14 08:54 UTC
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.400
3. Install Aspire 8.1.0
> dotnet workload update
> dotnet workload install aspire
4. Install azd [1.9.6]
5. Install Git [2.45.2]

**REPRO STEPS**
1. Open CMD, creating an Aspire Starter App using following commands:
>dotnet new aspire-starter -o aspirestarter 
>cd aspirestarter
2. Run `azd init`, select 'Use code in the current directory' > Confirm and continue initializing my app > type a new environment name, press enter
3. Run `azd auth login` to log in azd.
4. Run `azd up`

> Azure Subscription: WTE
> Azure location: East US

**ACTUAL**
Loading time takes too long when Creating/Updating resources (Container Apps Environment), and an error occurred:

 (x) Failed: Container Apps Environment: cae-56g44rgjfs2dk
  |   ====| Creating/Updating resources
ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:

![image](https://github.com/user-attachments/assets/9a9fd838-eb34-4c09-bb7e-a3b93f7b8ac8)

**EXPECTED**
The project can be deployed successfully.

**Comment by rajeshkamal5050** [comment] 2024-08-14 16:20
@v-xuto can you try reproducing it? see if any difference between 1.9.5 vs 1.9.6?

**Comment by vmykagapuz** [comment] 2024-08-15 03:13
This issue is only reproduce in East US, not in East US 2, West US and South Central US.

**Comment by zedy-wj** [comment] 2024-08-15 09:23
@rajeshkamal5050 , @vmykagapuz - We were able to reproduce this issue in both `1.9.5` and `1.9.6` azd releases, but this issue does not exist in daily version of azd.

**Comment by Rita003** [comment] 2024-08-16 07:22
This issue also repro on all location (eg: East US 2/ West US / South Central US/ Central US...) after installing the latest released azd v1.9.6 in today's validation, this issue also repro after installing daily azd [azd version 1.10.0-beta.1-daily.4051655] in today's validation.
This issue blocked our publish scenario today.

**Comment by rajeshkamal5050** [comment] 2024-08-17 07:19
Duplicate of #4221

**Closed by rajeshkamal5050** 2024-08-17 07:19 UTC
Labels: aspire

**Comment by vmykagapuz** [comment] 2024-08-22 10:03
I verified that this issue is fixed and is not reproduce for today's task.
