### ISSUE TITLE
[CI/CD Issues] templates-tests: 503 Site Unavailable

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#1032] opened 2022-10-28 19:02 UTC
See error here:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1950522&view=logs&j=c946be7e-04bd-5271-38f1-767d2c14093b&t=00d1c6df-7408-5c6a-8799-0d0fabd2515c&l=72

Gate: TestTemplates Azure-Samples_todo-nodejs-mongo-swa-func

```
Azure resource provisioning completed successfully
View the resources created under the resource group rg-azd-template-test-todo-nodejs-mongo-swa-func-1950522 in Azure Portal:

Deploying apps for azd-template-test-todo-nodejs-mongo-swa-func-1950522...
Deploying service api...
Deploying service api... |
- Preparing packaging... /
- Installing dependencies... -
- Building service... \
- Copying deployment package... |
- Compressing deployment artifacts... /
- Compressing deployment artifacts... -
- Publishing deployment package... \
Error: deploying service: deploying service api package: POST https://func-api-vgd23mngwcnpk.scm.azurewebsites.net/api/zipdeploy
--------------------------------------------------------------------------------
RESPONSE 503: 503 Site Unavailable
ERROR CODE UNAVAILABLE
--------------------------------------------------------------------------------
The service is unavailable.
--------------------------------------------------------------------------------

```

**Comment by vhvb1989** [comment] 2022-10-28 19:06
One more time from TestTemplates Azure-Samples_todo-python-mongo-swa-func:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1947117&view=logs&j=5bedfb69-28ae-5f77-30fa-7c40a887e2a4&t=79d95b2f-ee9d-5867-2699-970000986b2c&l=126

**Comment by vhvb1989** [comment] 2022-10-28 19:07
Note: both instances coming from `swa` templates

**Comment by vhvb1989** [comment] 2022-10-28 19:14
One More:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1941119&view=logs&j=5bedfb69-28ae-5f77-30fa-7c40a887e2a4&s=96ac2280-8cb4-5df5-99de-dd2da759617d&t=79d95b2f-ee9d-5867-2699-970000986b2c&l=87

Gate: TestTemplates Azure-Samples_todo-python-mongo-swa-func

**Comment by vhvb1989** [comment] 2022-10-28 19:32
One More:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1947117&view=logs&j=5bedfb69-28ae-5f77-30fa-7c40a887e2a4&t=79d95b2f-ee9d-5867-2699-970000986b2c&l=126

Gate: TestTemplates Azure-Samples_todo-python-mongo-swa-func

**Comment by weikanglim** [comment] 2022-10-31 21:43
I confirmed that all our clients that take advantage of the Azure SDK for Go's `pipeline` concept have built-in retry policies. The failures we're seeing already include retries.

We retry with 3 attempts with an exponential backoff that looks like ~0.8s, ~2.4s, ~5.6s. In total, this is ~8.8s of waiting time for `zipdeploy` API to recover, and yet these provisions still fail. It is unclear that waiting longer means that the service recovers. We can increase 1 retry attempt to make it a 20-second wait, but I'd be hesitant to increase any further without us working with the service teams to diagnose each individual failure.

**Comment by rajeshkamal5050** [comment] 2022-11-01 16:40
Removing blocker given that we had two successful runs of template test pipelines
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1958443&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1957561&view=results

We can monitor for some more time and close it if they become stable.

**Closed** 2022-11-03 16:20 UTC
Labels: flaky test

**Comment by pamelafox** [comment] 2023-05-10 21:44
I am seeing this issue today with App Service:

```
flask-db-quiz-example % azd up                              

Packaging services (azd package)

  (✓) Done: Packaging service web
- Package Output: /var/folders/nq/2sq7jzp17tl97sgxzbptr2d80000gn/T/azddeploy4038368612.zip

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time

You can view detailed progress in the Azure Portal:
https://portal.azure.com/#blade/HubsExtension/DeploymentDetailsBlade/overview/id/%2Fsubscriptions%2F32ea8a26-5b40-4838-b6cb-be5c89a57c16%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Fflask-db-quiz-example

(✓) Done: Resource group: flask-db-quiz-example-rg
(✓) Done: Log Analytics workspace: flask-db-quiz-example-34o7asrup2gdo-loganalytics
(✓) Done: App Service plan: flask-db-quiz-example-34o7asrup2gdo-serviceplan
(✓) Done: App Service: flask-db-quiz-example-34o7asrup2gdo-appservice
(✓) Done: Azure Database for PostgreSQL flexible server: flask-db-quiz-example-34o7asrup2gdo-postgresql


Deploying services (azd deploy)

  (x) Failed: Deploying service web

ERROR: failed deploying service 'web': failing invoking action 'deploy', deploying service web: POST https://flask-db-quiz-example-34o7asrup2gdo-appservice.scm.azurewebsites.net/api/zipdeploy
--------------------------------------------------------------------------------
RESPONSE 503: 503 Site Unavailable
ERROR CODE UNAVAILABLE
--------------------------------------------------------------------------------
The service is unavailable.
--------------------------------------------------------------------------------
```

I am guessing that my resource is in some sort of bad state, as I also see some weirdness in the Portal. Deployment Center > Logs says "Failed to load deployment logs: Too many requests. Please try again later."

I'll try with a different resource group.

**Comment by weikanglim** [comment] 2023-05-11 01:08
@pamelafox If you can reproduce it consistently, let's chat and follow up with service teams.

**Comment by pamelafox** [comment] 2023-05-11 16:04
I can still reproduce this morning, yes. I filed a support request in Portal yesterday, haven't heard back on it yet.

**Comment by pamelafox** [comment] 2023-05-12 02:28
It only happens when I try to downgrade App Service Plan to F1 from a higher tier (B1 or S1). It's fine if I deploy at higher tier or deploy F1 from scratch. Probably fine to not worry about this issue since downgrading to F1 is atypical.
